/* Futures Friends website statistics: connection to OUR self-hosted, cookieless analytics server (Umami).
   With an empty url or siteId, analytics.js sends nothing at all and window.ffTrack does nothing.

   PRODUCTION: the line below is WRITTEN BY A SCRIPT at go-live, never by hand:
     node tools/set-analytics-config.mjs /Volumes/FFCRM/app/deploy/out/hub-public.json
   (that file is produced by the CRM repo's deploy/push.sh; deploy/site-config.sh runs this tool). It accepts only
   https://ff-stats.dvolcore.com and a website id (UUID). Both values are PUBLIC: never put a secret in a file served to browsers.

   LOCAL: copy analytics-config.local.js.example to analytics-config.local.js (git-ignored) and fill in the local website id.
   That file is only ever loaded from localhost / 127.0.0.1.
   What is collected, and what never is: docs/analytics/ANALYTICS_PLAN.md in the CRM repo and the Privacy page. */
window.FF_ANALYTICS = { url: '', siteId: '' }; // @generated by tools/set-analytics-config.mjs
(function () {
  var h = location.hostname;
  if (h === 'localhost' || h === '127.0.0.1') {
    document.write('<script src="analytics-config.local.js"><\/script>');
  }
})();
