/* Spanish (DRAFT) caption tracks and transcripts: subtitles of the English audio, translated; pending review by the center's Spanish
   teacher. captions.js adds each as a second <track kind="subtitles" srclang="es" label="Español (borrador)">, and shows the Spanish
   transcript when the site language is Spanish. Glossary: 09_Training_and_Curriculum/bilingual/GLOSSARY_ES.md (owner decision 2026-10-07). */
(function () {
'use strict';
window.FFCaptionsES = Object.freeze({
  "video/academy-welcome.mp4": { vtt: "video/academy-welcome.es.vtt", transcript: "[Tarjeta de título] Academia de Formación de Futures Friends. Conoce a los amigos: Booker, Lumi, Zuri y Bop. Cuatro amigos, cuatro pilares, un programa.\n\nMs. June: Bienvenidos a la Academia de Formación de Futures Friends. Soy Ms. June, maestra de nuestro mundo de cuentos. Aquí, las personas adultas aprenden cómo trabajan los amigos en el salón.\n\nMs. June: Conozcamos a los cuatro amigos. Cada uno se encarga de dos pilares del día integral del niño.\n\n[Tarjeta: Booker, el pequeño aprendiz valiente. Pilares: Aprender, Sonreír.] Booker: ¡Hola! Soy Booker. ¡Me encanta aprender, aunque sea difícil! Ms. June: Booker se encarga de Aprender y Sonreír.\n\n[Tarjeta: Lumi, la guardiana de la bondad. Pilares: Pertenecer, Calma.] Lumi: ¡Soy Lumi! Ayudo a que todos sientan que pertenecen. Ms. June: Lumi se encarga de Pertenecer y Calma.\n\n[Tarjeta: Zuri, la exploradora curiosa. Pilares: Explorar, Nutrir.] Zuri: ¡Soy Zuri! ¡Vamos a explorar y a descubrirlo juntos! Ms. June: Zuri se encarga de Explorar y Nutrir.\n\n[Tarjeta: Bop, el gran movedor. Pilares: Moverse, Al aire libre.] Bop: ¡Y yo soy Bop! ¡Mueve tu cuerpo, crece tu mente! Ms. June: Bop se encarga de Moverse y Al aire libre.\n\nMs. June: Nuestro ciclo de aprendizaje tiene seis pasos: ver, conversar, hacer, moverse, explorar, llevar a casa. «Llevar a casa» les da a las familias una pregunta y una actividad para compartir.\n\nMs. June: Usa a los amigos como señales constantes. Bop: ¿Listos? ¡Bop y a moverse! Ms. June: ...significa que es hora de moverse. El Rato Tranquilo de Lumi invita a todos a ir más despacio.\n\nMs. June: Lo siguiente es el Nivel 1 planificado, Fundamentos: zonas de aprendizaje, salud y seguridad, y rutinas diarias. El Nivel 2 profundiza en la zona de cada amigo. [Tarjeta: Niveles planificados de Futures Friends, no credenciales estatales. Los cursos están en desarrollo; hasta que un curso se apruebe, no cuenta para las horas de capacitación obligatorias.]\n\nMs. June: Los episodios y los cursos aún están en desarrollo, y ningún curso cuenta para las horas de capacitación obligatorias hasta que se apruebe. Pasos pequeños, grandes historias.\n\n[Tarjeta final] Academia de Formación de Futures Friends. Pasos pequeños. Grandes historias. Personajes del mundo de cuentos. Los episodios y los cursos están en desarrollo." },
  "video/act-elephant-stomp.mp4": { vtt: "video/act-elephant-stomp.es.vtt", transcript: "[Tarjeta de título] Futures Friends. Pausa de movimiento: Pisotón y vaivén del elefante. Muévete con Bop.\n\n[En pantalla: tarjetas con dibujos muestran cada movimiento cuando Bop lo nombra: Pisa fuerte, Balancéate, ¡Estatua!, Mueve tu trompa, Más despacio, Siéntate, Palmaditas en las rodillas, Trompa grande, Muy calladito, Palmaditas calladitas, Trompa lenta y calladita, Párate bien alto.]\n\nBop: ¡Hola, amigos! Soy Bop.\n\nBop: ¡Pisa fuerte conmigo! ¡Derecha, izquierda!\n\nBop: Ahora balancéate, balancéate, como un árbol tranquilo.\n\nBop: ¡Uno, dos! ¡Te toca!\n\nBop: ¡Pisa fuerte y balancéate! ¡Muy bien!\n\nBop: Estatua... ¡lo lograste!\n\nBop: ¿Listos? ¡Bop y a moverse!\n\nBop: ¡Hagámoslo otra vez!\n\nBop: Pisa fuerte con tus pesadas patas de elefante...\n\nBop: ¡Uno, dos, tres!\n\nBop: Ahora mueve tu trompa de lado a lado...\n\nBop: Swish... ¡swish!\n\nBop: Más... despacio...\n\nBop: Ahora eres un elefante con sueño.\n\nBop: Shhh... elefante con sueño.\n\nBop: ¡Buenos días, elefante! ¡Hora de despertar!\n\nBop: Seamos elefantes sentados.\n\nBop: ¡Todos pueden hacerlo!\n\nBop: Date palmaditas en las rodillas como patas de elefante...\n\nBop: ¡Uno, dos, tres!\n\nBop: Ahora haz una trompa grande con los dos brazos.\n\nBop: Balancea... y balancea... ¡y balancea!\n\nBop: ¡Tarán!\n\nBop: ¡Sentado o de pie, lo lograste!\n\nBop: Ahora hagámoslo muy, muy calladito.\n\nBop: Shhh.\n\nBop: Palmaditas calladitas en las rodillas...\n\nBop: Uno, dos, tres.\n\nBop: Ahora una trompa lenta y calladita.\n\nBop: Tararea conmigo. [Bop tararea suavemente]\n\nBop: ¡Ahora pongámonos de pie, bien altos!\n\nBop: ¡Ahora pisemos fuerte juntos, bien grande!\n\nBop: ¡Uno... dos... tres!\n\nBop: ¡Ahora haz una trompa grande!\n\nBop: Balancéate como un árbol tranquilo...\n\n[Tarjeta final] ¡Qué bien se movieron, amigos! Aprende. Muévete. Explora. Pertenece. Una pausa de movimiento de Futures Friends." },
  "video/act-trunk-reach.mp4": { vtt: "video/act-trunk-reach.es.vtt", transcript: "[Tarjeta de título] Futures Friends. Pausa de movimiento: Estira la trompa. Muévete con Bop.\n\n[En pantalla: tarjetas con dibujos muestran cada movimiento cuando Bop lo nombra: Manzana, Allá arriba, Estírate bien alto.]\n\nBop: ¡Hola, amigos! Soy Bop.\n\nBop: ¡Juguemos a Estira la trompa!\n\nBop: ¡Hay una manzana allá arriba!\n\nBop: Estira tu trompa bien alto... ¡y tómala!\n\nBop: ¿Qué tan alto puede llegar tu trompa hoy?\n\nBop: ¡Qué rico! ¡Una manzana!\n\n[Tarjeta final] ¡Qué bien se estiraron, amigos! Aprende. Muévete. Explora. Pertenece. Una pausa de movimiento de Futures Friends." },
  "video/act-freeze-try-again.mp4": { vtt: "video/act-freeze-try-again.es.vtt", transcript: "[Tarjeta de título] Futures Friends. Pausa de movimiento: Estatua y otra vez. Muévete con Bop.\n\n[En pantalla: tarjetas con dibujos muestran cada movimiento cuando Bop lo nombra: ¡Baila!, ¡Estatua!, ¡Inténtalo otra vez!, Marcha.]\n\nBop: ¡Hola, amigos! Soy Bop.\n\nBop: ¡Juguemos a Estatua y otra vez!\n\nBop: Cuando pare la música... ¡estatua!\n\n[Bop tararea con la música]\n\n[Para la música] ¡Estatua!\n\n[Bop se ríe]\n\nBop: ¡Ahora vuelve a intentarlo!\n\n[Bop tararea con la música]\n\n[Para la música] ¡Estatua!\n\n[Bop se ríe]\n\nBop: ¡Ahora vuelve a intentarlo!\n\nBop: ¡Marcha conmigo, rodillas bien arriba!\n\n[Bop tararea con la música]\n\n[Para la música] ¡Estatua!\n\nBop: ¡Ahora vuelve a intentarlo!\n\n[Bop se ríe y tararea con la música]\n\n[Tarjeta final] ¡Qué bien se congelaron, amigos! Aprende. Muévete. Explora. Pertenece. Una pausa de movimiento de Futures Friends." },
  "video/act-animal-walks.mp4": { vtt: "video/act-animal-walks.es.vtt", transcript: "[Tarjeta de título] Futures Friends. Pausa de movimiento: Caminatas de animales. Muévete con Bop.\n\n[En pantalla: tarjetas con dibujos muestran cada movimiento cuando Bop lo nombra: Elefante, Oso, Conejito, Salta como un conejito.]\n\nBop: ¡Hola, amigos! Soy Bop.\n\nBop: ¡Hagamos Caminatas de animales!\n\nBop: ¿Qué animal vas a ser?\n\nBop: Primero seré un elefante.\n\nBop: ¡Pasos grandes y pesados!\n\nBop: ¡Cambio! ¡Ahora camina como un oso grande!\n\nBop: ¿Puedes caminar como un oso?\n\nBop: Párate bien alto conmigo.\n\nBop: ¡Cambio! ¡Ahora salta como un conejito!\n\nBop: Saltitos pequeños. ¿Listos?\n\nBop: ¿Puedes saltar como un conejito?\n\nBop: ¡Salta conmigo!\n\n[Música alegre]\n\n[Tarjeta final] ¡Qué bien caminaron, amigos! Aprende. Muévete. Explora. Pertenece. Una pausa de movimiento de Futures Friends." },
  "video/act-flamingo-balance.mp4": { vtt: "video/act-flamingo-balance.es.vtt", transcript: "[Tarjeta de título] Futures Friends. Pausa de movimiento: Equilibrio de flamenco. Muévete con Bop.\n\n[En pantalla: tarjetas con dibujos muestran cada movimiento cuando Bop lo nombra: Párate derecho, Levanta un pie, ¡Tambalearse está bien!, El otro pie, Ala de flamenco.]\n\nBop: ¡Hola, amigos! Soy Bop.\n\nBop: ¡Seamos flamencos!\n\nBop: ¡Es Equilibrio de flamenco!\n\nBop: Párate derecho y agárrate de la pared o de la mano de una persona adulta.\n\nBop: Levanta un pie un poquito... ¡y cuenta conmigo!\n\nBop: ¡Uno... dos... tres... cuatro... cinco!\n\nBop: ¡Tambalearse está bien!\n\nBop: ¿Listos para el otro pie?\n\nBop: ¡Ahora el otro pie!\n\nBop: Levántalo un poquito... ¡y cuenta conmigo!\n\nBop: ¡Uno... dos... tres... cuatro... cinco!\n\nBop: ¡Tambalearse está bien!\n\nBop: ¡Ahora sé un flamenco con un ala!\n\nBop: Estira el otro brazo bien abierto.\n\nBop: ¡Uno... dos... tres... cuatro... cinco!\n\n[Tarjeta final] ¡Qué buen equilibrio, amigos! Aprende. Muévete. Explora. Pertenece. Una pausa de movimiento de Futures Friends." },
  "video/act-clap-back.mp4": { vtt: "video/act-clap-back.es.vtt", transcript: "[Tarjeta de título] Futures Friends. Pausa de movimiento: Palmas de eco. Muévete con Bop.\n\n[En pantalla: tarjetas con dibujos muestran cada movimiento cuando Bop lo nombra: Escucha, ¡Te toca!.]\n\nBop: ¡Hola, amigos! Soy Bop.\n\nBop: ¡Juguemos a Palmas de eco!\n\nBop: Yo aplaudo... y tú me devuelves las palmas.\n\nBop: ¡Escucha!\n\n[¡Palmada! ¡Palmada! ¡Palmada!]\n\nBop: ¡Te toca!\n\nBop: ¡Escucha!\n\n[¡Palmada! ¡Palmada! ¡Palmada!]\n\nBop: ¡Te toca!\n\nBop: ¡Muy buenas palmas!\n\nBop: ¡Pronto te tocará dirigir!\n\nBop: ¡Escucha! Una palmada... y luego dos.\n\n[¡Palmada!] ... [¡Palmada! ¡Palmada!]\n\nBop: ¡Te toca!\n\nBop: ¡Escucha! Dos palmadas... y luego una.\n\n[¡Palmada! ¡Palmada!] ... [¡Palmada!]\n\nBop: ¡Te toca!\n\nBop: ¡Escuchaste la pausa!\n\nBop: ¡Qué bien escuchaste!\n\n[Tarjeta final] ¡Qué bien aplaudieron, amigos! Aprende. Muévete. Explora. Pertenece. Una pausa de movimiento de Futures Friends." },
  "video/act-peekaboo-turns.mp4": { vtt: "video/act-peekaboo-turns.es.vtt", transcript: "[Tarjeta de título] Futures Friends. A jugar juntos: Turnos de cucú. Con Lumi.\n\nLumi: Hola, bebé. Soy yo, Lumi.\n\nLumi: Juguemos al cucú.\n\nLumi: ¿Dónde está Lumi?\n\nLumi: ¡Cucú!\n\nLumi: ¡Ohh, sonreíste!\n\nLumi: Juguemos otra vez.\n\nLumi: ¿Dónde está Lumi?\n\nLumi: ¡Cucú!\n\nLumi: ¡Te escuché!\n\nLumi: Esta vez... despacito.\n\nLumi: ¡Cu... cú... tras!\n\nLumi: Mira. Un pañuelo suave.\n\nLumi: ¿Dónde está Lumi?\n\nLumi: ¡Cucú!\n\nLumi: ¡Me encontraste!\n\nLumi: ¡Te veo!\n\n[Tarjeta final] ¡Hasta pronto! Aprende. Muévete. Explora. Pertenece. Un video de Futures Friends para jugar juntos." },
  "video/act-bop-bubble-chase.mp4": { vtt: "video/act-bop-bubble-chase.es.vtt", transcript: "[Tarjeta de título] Futures Friends. Al aire libre: A perseguir burbujas. Muévete con Bop.\n\nBop: ¡Hola, amigos! Soy Bop.\n\nBop: ¡Burbujas! ¡Vamos a reventarlas!\n\nBop: ¡Estírate bien alto!\n\nBop: ¡Ahora revienta una con una palmada!\n\nBop: ¡Revienta una con tu trompa!\n\nBop: Pausa de burbujas. Un respiro grande.\n\n[Tarjeta final] ¡Qué bien reventaron las burbujas, amigos! Aprende. Muévete. Explora. Pertenece. Un video de Futures Friends para jugar juntos." },
  "video/act-zuri-color-walk.mp4": { vtt: "video/act-zuri-color-walk.es.vtt", transcript: "[Tarjeta de título] Futures Friends. Al aire libre: Paseo de colores. Explora con Zuri.\n\nZuri: ¡Hola, amigos! Soy Zuri.\n\nZuri: Vamos a dar un paseo de colores. ¡Mira a tu alrededor!\n\nZuri: ¡Verde! Pasto verde.\n\nZuri: ¡Blanco! Flores blancas.\n\nZuri: ¡Amarillo! El sol brillante.\n\nZuri: ¡Azul! El gran cielo azul.\n\nZuri: ¿Qué colores puedes encontrar?\n\n[Tarjeta final] ¡Qué bien encontraron colores, amigos! Aprende. Muévete. Explora. Pertenece. Un video de Futures Friends para jugar juntos." },
  "video/act-lumi-kind-words.mp4": { vtt: "video/act-lumi-kind-words.es.vtt", transcript: "[Tarjeta de título] Futures Friends. Palabras amables: Mira, escucha, echa una mano. Con Lumi.\n\nLumi: Hola, amigos. Soy Lumi.\n\nLumi: Cuando un amigo está solito, esto es lo que hacemos.\n\nLumi: Mira.\n\nLumi: Escucha.\n\nLumi: Echa una mano.\n\nLumi: ¿Quieres jugar conmigo?\n\nLumi: ¡Sí!\n\nLumi: Mira. Escucha. Echa una mano.\n\n[Tarjeta final] ¡Palabras amables, amigos! Aprende. Muévete. Explora. Pertenece. Un video de Futures Friends para jugar juntos." },
  "video/act-booker-first-sound.mp4": { vtt: "video/act-booker-first-sound.es.vtt", transcript: "[Tarjeta de título] Futures Friends. Juego de sonidos: La búsqueda del primer sonido. Con Booker.\n\nBooker: ¡Hola, amigos! Soy Booker.\n\nBooker: ¡Vamos a buscar sonidos! Escucha...\n\nBooker: Sss... sss... ¡«sun» (sol)!\n\nBooker: Ahora un sonido nuevo. T... t... ¡«tree» (árbol)!\n\nBooker: F... f... ¡«flower» (flor)!\n\nBooker: ¡Te toca! ¡Elige un sonido y búscalo en casa!\n\n[Tarjeta final] ¡Qué bien escucharon, amigos! Aprende. Muévete. Explora. Pertenece. Un video de Futures Friends para jugar juntos." },
  "video/act-lumi-calm-breath.mp4": { vtt: "video/act-lumi-calm-breath.es.vtt", transcript: "[Tarjeta de título] Futures Friends. Rincón de calma: Huele la flor, sopla la vela. Respira con Lumi.\n\nLumi: Hola, amigos. Soy Lumi.\n\nLumi: Cuando los sentimientos se hacen grandes, podemos respirar juntos.\n\nLumi: Aquí está mi flor... y mi vela.\n\nLumi: Huele la flor...\n\nLumi: Sopla la vela...\n\nLumi: ¿Cómo se siente tu cuerpo ahora?\n\n[Tarjeta final] ¡A respirar con calma, amigos! Aprende. Muévete. Explora. Pertenece. Un video de Futures Friends para jugar juntos." },
  "video/act-zuri-wonder-loop.mp4": { vtt: "video/act-zuri-wonder-loop.es.vtt", transcript: "[Tarjeta de título] Futures Friends. Hora de asombro: El ciclo de curiosidad de Zuri. Explora con Zuri.\n\nZuri: ¡Hola, amigos! Soy Zuri.\n\nZuri: Observa. ¿Qué ves?\n\nZuri: ¡Pétalos chiquititos!\n\nZuri: Adivina. ¿Qué pasará si le soplo?\n\nZuri: ¡Probemos!\n\nZuri: ¿Fue lo que pensabas? ¡Se meneó!\n\nZuri: Me pregunto, me pregunto... ¿qué pasa si lo intentamos?\n\n[Tarjeta final] ¡Qué buena curiosidad, amigos! Aprende. Muévete. Explora. Pertenece. Un video de Futures Friends para jugar juntos." },
  "video/act-lumi-feelings-faces.mp4": { vtt: "video/act-lumi-feelings-faces.es.vtt", transcript: "[Tarjeta de título] Futures Friends. Sentimientos: Caras de sentimientos. Con Lumi.\n\nLumi: Hola, amigos. Soy Lumi.\n\nLumi: Hagamos caras de sentimientos. ¡Imítame!\n\nLumi: ¡Feliz!\n\nLumi: Triste.\n\nLumi: ¡Sorprendida!\n\nLumi: Con sueño...\n\nLumi: Todos los sentimientos están bien.\n\n[Tarjeta final] ¡Qué buenas caras, amigos! Aprende. Muévete. Explora. Pertenece. Un video de Futures Friends para jugar juntos." },
  "video/act-booker-brave-reader.mp4": { vtt: "video/act-booker-brave-reader.es.vtt", transcript: "[Tarjeta de título] Futures Friends. A leer juntos: Pasos del lector valiente. Lee con Booker.\n\nBooker: ¡Hola, amigos! Soy Booker.\n\nBooker: ¿Una palabra nueva? ¡Seamos lectores valientes!\n\n[En pantalla: una tarjeta de palabra con el dibujo de una cometa roja del libro de Booker, la palabra KITE («cometa» en inglés) en letras grandes y kite en letras pequeñas debajo.]\n\nBooker: Primero, mira el dibujo para encontrar una pista.\n\n[Paso 1, Mira el dibujo: se ilumina el dibujo de la cometa. ¡Pista!]\n\nBooker: Di el primer sonido... kuh, kuh, kuh (el sonido /k/).\n\n[Paso 2, Di el primer sonido: se ilumina la letra K, con /k/ debajo.]\n\nBooker: Desliza el dedo, lento como la miel.\n\n[Paso 3, Desliza el dedo: una patita se desliza bajo K, I, T, E y cada letra se ilumina: k... i... t...]\n\nBooker: ¡«Kite» (cometa)!\n\n[Paso 4, Lee la palabra: se ilumina toda la palabra KITE.]\n\nBooker: ¿No salió? No pasa nada.\n\nBooker: Respiro grande. Corazón valiente. ¡Puedo intentarlo otra vez!\n\n[En pantalla: Respiro grande. Corazón valiente. ¡Puedo intentarlo otra vez!]\n\n[Tarjeta final] ¡Qué buena lectura, amigos! Aprende. Muévete. Explora. Pertenece. Un video de Futures Friends para jugar juntos." },
  "video/ff-intro-titled-16x9.mp4": { vtt: "video/ff-intro-titled.es.vtt", transcript: "[Título] El logo de fieltro de Futures Friends llega volando: Conoce a los Futures Friends\n\nBooker: ¡Hola! Soy Booker. ¡Me encanta aprender, aunque sea difícil!\n\nLumi: ¡Soy Lumi! Ayudo a que todos sientan que pertenecen.\n\nZuri: ¡Soy Zuri! ¡Vamos a explorar y a descubrirlo juntos!\n\nBop: ¡Y yo soy Bop! ¡Mueve tu cuerpo, crece tu mente!\n\nLos cuatro amigos: ¡Somos los Futures Friends!\n\n[Tarjeta final] Futures Friends. Aprende. Muévete. Explora. Pertenece. Futures Friends · un programa de Futures Learning Center" },
  "video/ff-intro-titled-4x5.mp4": { vtt: "video/ff-intro-titled.es.vtt", transcript: "[Título] El logo de fieltro de Futures Friends llega volando: Conoce a los Futures Friends\n\nBooker: ¡Hola! Soy Booker. ¡Me encanta aprender, aunque sea difícil!\n\nLumi: ¡Soy Lumi! Ayudo a que todos sientan que pertenecen.\n\nZuri: ¡Soy Zuri! ¡Vamos a explorar y a descubrirlo juntos!\n\nBop: ¡Y yo soy Bop! ¡Mueve tu cuerpo, crece tu mente!\n\nLos cuatro amigos: ¡Somos los Futures Friends!\n\n[Tarjeta final] Futures Friends. Aprende. Muévete. Explora. Pertenece. Futures Friends · un programa de Futures Learning Center" },
  "video/moments/ff-moment-lumi-hello-choices.mp4": { vtt: "video/moments/ff-moment-lumi-hello-choices.es.vtt", transcript: "Lumi: ¿Abrazo, chócala, saludo o espacio?\n\nNueva amistad: Saludo.\n\nZuri: Con un ojo sí sale. Mmm." },
  "video/moments/ff-moment-zuri-small-wave.mp4": { vtt: "video/moments/ff-moment-zuri-small-wave.es.vtt", transcript: "Zuri: Con los dos ojos es más difícil.\n\nNueva amistad: Puedes intentarlo.\n\nZuri: Saludo pequeño. ¿Igual de feliz?" },
  "video/moments/ff-moment-bop-two-waves.mp4": { vtt: "video/moments/ff-moment-bop-two-waves.es.vtt", transcript: "Bop: Dos saludos.\n\nNueva amistad: Elige uno." },
  "video/moments/ff-moment-lumi-hands-close.mp4": { vtt: "video/moments/ff-moment-lumi-hands-close.es.vtt", transcript: "Lumi: Casi te abrazo.\n\nNueva amistad: Las manos pueden quedarse aquí.\n\nLumi: Aquí." },
  "video/moments/ff-moment-booker-watch-first.mp4": { vtt: "video/moments/ff-moment-booker-watch-first.es.vtt", transcript: "Booker: Puedes mirar primero." },
  "video/cast/ff-cast-june-welcome.mp4": { vtt: "video/cast/ff-cast-june-welcome.es.vtt", transcript: "Toda persona adulta en el salón empieza como aprendiz. Veamos de cerca lo que ese aprendizaje le pide." },
  "video/cast/ff-cast-june-two-questions.mp4": { vtt: "video/cast/ff-cast-june-two-questions.es.vtt", transcript: "En nuestro mundo de cuentos, les hago dos preguntas a los niños. Una buena capacitación les hace las mismas dos a los adultos." },
  "video/cast/ff-cast-june-small-steps.mp4": { vtt: "video/cast/ff-cast-june-small-steps.es.vtt", transcript: "Pasos pequeños. Grandes historias. Un equipo aprende igual que los niños: un paso claro, practicado hasta que se afianza." },
  "video/cast/ff-cast-june-notice-wonder.mp4": { vtt: "video/cast/ff-cast-june-notice-wonder.es.vtt", transcript: "¿Qué observas en tu equipo? ¿Qué te preguntas? Lleva las dos preguntas a la conversación." },
  "video/cast/ff-cast-hazel-law.mp4": { vtt: "video/cast/ff-cast-hazel-law.es.vtt", transcript: "Lo primero es lo primero: antes de que una persona adulta enseñe, la ley pregunta quién es y si está lista." },
  "video/cast/ff-cast-moss-standard.mp4": { vtt: "video/cast/ff-cast-moss-standard.es.vtt", transcript: "Conocer la regla es el comienzo. Demostrarla, cada día, es el estándar." },
  "video/cast/ff-cast-fern-safety.mp4": { vtt: "video/cast/ff-cast-fern-safety.es.vtt", transcript: "Si una persona adulta falla una pregunta de seguridad, vuelve a aprenderla. Eso no es un fracaso. De eso se trata." },
});
})();
