/* Character-led curriculum explorer. Selections stay local; no child data is collected. */
(function () {
  'use strict';
  const ages = {
    twos: {name:'Twos', range:'Ages 2 to 3', summary:'Little discoveries. Big first steps.', skills:['Name pictures and join in with songs','Match colors and count a few objects','Name happy and sad; practice taking turns','Wash hands with help and move to music','Explore paint, rhythm and pretend play']},
    threes: {name:'Threes', range:'Ages 3 to 4', summary:'More questions. More ways to grow.', skills:['Retell a story and recognize a name','Sort, count and test sink or float','Name feelings and wait for a turn','Practice routines and serve with help','Make collages and act out stories']},
    prek: {name:'Pre-K', range:'Ages 4 to 5', summary:'Ready to try. Ready for what comes next.', skills:['Explore letter sounds and story sequences','Build patterns and predict then test','Solve problems with words and help friends','Practice self-serving and supervised scissors','Create self-portraits, drama and music']}
  };
  const domains = ['Literacy','Math & science','Social-emotional','Physical development','Creative arts'];
  const symbols = ['BookOpen','Leaf','Heart','Waves','Sparkles'];
  const colors = ['#2158b4','#25815b','#b43177','#8236AE','#7050ad'];
  const friendColors = {booker:'#2158b4',lumi:'#b43177',zuri:'#25815b',bop:'#6B2A8E'};
  const activities = {
    booker:{title:'A story in three pictures', time:'10 minutes', material:'A favorite picture book', steps:['Look through the pictures together.','Choose a beginning, middle and ending.','Tell the story in your own words.'], adapt:{twos:'Point to a favorite picture and name what you see.', threes:'Put three story moments in order with a grown-up.', prek:'Retell the story and imagine a different ending.'}},
    lumi:{title:'A little kindness goes a long way',time:'5 minutes',material:'Paper and crayons',steps:['Draw a face for how you feel today.','Talk about something that helps when feelings get big.','Choose one kind thing to do together.'],adapt:{twos:'Point to a happy or sad face; a grown-up names the feeling.',threes:'Name a feeling and practice asking for a turn.',prek:'Describe a feeling and suggest a way to help a friend.'}},
    zuri:{title:'The color discovery walk',time:'10 minutes',material:'A safe indoor space or supervised outdoor path',steps:['Choose a color before you start.','Find three things that match.','Compare their shapes, sizes and textures.'],adapt:{twos:'Find one color together and name each match.',threes:'Sort discoveries into two color groups.',prek:'Make a prediction, then count and compare your findings.'}},
    bop:{title:'Move, freeze, try again',time:'5 minutes',material:'A clear space and a favorite song',steps:['Choose a movement: march, stretch or sway.','Move with the music; pause when the music stops.','Let your child choose the next movement.'],adapt:{twos:'Copy one simple movement with a grown-up.',threes:'Try two movements and take turns leading.',prek:'Create a three-movement pattern for everyone to follow.'}}
  };
  let month = 0, week = 0, friend = 'booker';
  const days = new Set(['Monday','Wednesday','Friday']);
  const icon = name => `<svg class="px-icon" aria-hidden="true"><use href="img/ui-icons.svg#${name}"></use></svg>`;
  const age = () => ages[st.age] ? st.age : 'threes';
  // Character art from the plush library (FFPlush, plush-cast.js): srcset 480/960, the manifest's intrinsic size.
  // Zuri (EXPLORE) carries her magnifier on the curriculum page (wave 5 generated pose); the others stand.
  const POSE = { zuri: 'magnifier' };
  const art = key => window.FFPlush ? window.FFPlush.img(POSE[key] ? window.FFPlush.pose(key, POSE[key]) : key, { alt: CH[key].n, h: 345 }) : `<img src="${ART[key]}" alt="${CH[key].n}">`;
  // Story-world classmates for each age band (wave 5): children only, drawn at their true size, always labelled.
  const classmates = { twos: ['tad', 'mimi'], threes: ['nico', 'poppy'], prek: ['finn', 'tilly'] };
  const bandCast = k => window.FFSupporting && window.FFSupporting.cameo ? window.FFSupporting.cameo(classmates[k], { unit: 150, cls: 'ex-agecameo' }) : '';
  // The activity happens on the story-world activity rug (img/plush/environments), labelled as an illustration.
  const room = () => window.FFPlush ? window.FFPlush.env('activity-rug', { cls: 'ex-room', alt: '', sizes: '(max-width:680px) 92vw, 460px' }) + (window.FFArt ? window.FFArt.flag('illustration', { title: 'Illustration', line: 'The storybook classroom, not a photo of our center', cls: 'ex-roomflag' }) : '') : '';
  function agePanel(){
    const a = ages[age()];
    return `<div class="ex-ageheading"><div><span class="ex-kicker">${a.range}</span><h3>${a.summary}</h3><span class="ex-note">Development preview</span></div>${bandCast(age())}</div><div class="ex-skills">${a.skills.map((s,i)=>`<div class="ex-skill" style="--accent:${colors[i]}">${icon(symbols[i])}<h4>${domains[i]}</h4><p>${s}</p></div>`).join('')}</div>`;
  }
  function journey(){
    const u = D.units[month], w = u.weeks[week], key = charOf(w[2]);
    return `<div class="ex-unithead"><div><span class="ex-kicker">${MONTHS[month]} / Unit ${u.n}</span><h3>${esc(u.title)}</h3></div><span class="ex-note">4 theme weeks</span></div><div class="ex-weeks" role="group" aria-label="Theme week">${u.weeks.map((item,i)=>`<button type="button" data-ex-week="${i}" aria-pressed="${i===week}"><small>Week ${esc(item[0])}</small><b>${esc(item[1])}</b></button>`).join('')}</div><div class="ex-weekdetail" style="--accent:${friendColors[key]}"><div class="ex-guide">${art(key)}<span>${esc(w[2])}</span></div><div class="ex-weekcopy"><span class="ex-kicker">This week's discovery</span><h3>${esc(w[1])}</h3><dl><div><dt>${icon('Play')} Episode plan</dt><dd>${esc(w[3])}</dd></div><div><dt>${icon('BookOpen')} Story pairing</dt><dd>${esc(w[4])}</dd></div><div><dt>${icon('LayoutDashboard')} Bring it home</dt><dd>${esc(w[5])}</dd></div></dl><button type="button" class="px-btn px-primary" data-anchor="family-plan">Build a family plan ${icon('ChevronDown')}</button></div></div>`;
  }
  function activity(){
    const a = activities[friend];
    return `<div class="ex-activityart${room() ? ' ex-activityart-room' : ''}" style="--accent:${friendColors[friend]}">${room()}${art(friend)}<span>${CH[friend].p}</span></div><div class="ex-activitycopy"><span class="ex-kicker">${a.time} / With a grown-up</span><h3>${a.title}</h3><p><b>You'll need:</b> ${a.material}</p><ol>${a.steps.map(s=>`<li>${s}</li>`).join('')}</ol><div class="ex-adapt"><b>${ages[age()].range}</b><p>${a.adapt[age()]}</p></div><p class="ex-note">Sample activity / Adult supervision required</p></div>`;
  }
  function planText(){
    const u = D.units[month], w = u.weeks[week], a = activities[friend];
    return ['FUTURES FRIENDS / FAMILY DISCOVERY PLAN','Development preview; not a published curriculum edition.',`${MONTHS[month]}: ${u.title}`,`Week ${w[0]}: ${w[1]}`,ages[age()].range,'',`Family connection: ${w[5]}`,`Story pairing (planned): ${w[4]}`,`Episode pairing (planned): ${w[3]}`,'',`Sample activity: ${a.title}`,`Time: ${a.time}`,`Materials: ${a.material}`,...a.steps.map((s,i)=>`${i+1}. ${s}`),`Age adaptation: ${a.adapt[age()]}`,'',`Discovery days: ${['Monday','Tuesday','Wednesday','Thursday','Friday'].filter(d=>days.has(d)).join(', ') || 'None selected'}`,'Adult supervision required. Adapt to each child; this is not an assessment.'].join('\n');
  }
  function planSummary(){return `<span class="ex-kicker">${MONTHS[month]} / ${ages[age()].range}</span><h3>${esc(D.units[month].weeks[week][1])}</h3><p>${esc(D.units[month].weeks[week][5])}</p><span class="ex-note">${days.size} discovery days / ${CH[friend].n}'s sample activity</span>`;}
  V.curriculum = () => `<div class="ex-curriculum">
    <section class="ex-hero${window.FFArt && window.FFArt.kitImg ? ' ffa-kit" data-kit-view="kit' : ''}">${window.FFArt ? window.FFArt.photoImg('turtle-rug', {cls: 'ex-heroimage', eager: true, sizes: '100vw'}) : ''}${window.FFArt && window.FFArt.kitImg ? window.FFArt.kitImg('turtle-rug', {cls: 'ex-heroimage ex-herokit', eager: true, sizes: '100vw'}) : ''}<div class="wrap ex-herocopy"><span class="ex-kicker">Curriculum / Ages 2 to 5</span><h1>Futures Friends<br><span>A year of discovery.</span></h1><p>Twelve monthly adventures. Four familiar friends. Little moments that invite children to read, play, explore and belong.</p><div class="ex-heroactions"><button type="button" class="px-btn px-primary" data-anchor="units">Explore the learning year ${icon('ArrowRight')}</button><button type="button" class="ex-herolink" data-anchor="ages">Find your age band ${icon('ChevronDown')}</button></div><span class="ex-heronote">12 units / 48 theme weeks / Curriculum in development: Units 1 to 4 written (draft; summary and a sample day public, full plans for licensed centers); Units 5 to 12 planned</span>${window.FFArt ? `<span class="ex-photocredit">${window.FFArt.kitImg ? `<b class="ex-kitlabel">${window.FFArt.KIT_LABEL}</b> (Lumi's Calm Corner added to the real photo; not installed yet). ` : ''}Photo: ${window.FFArt.CENTER_CREDIT}${window.FFArt.kitToggle ? window.FFArt.kitToggle('turtle-rug') : ''}</span>` : ''}</div><div class="ex-cast" aria-hidden="true">${KEYS.map(k=>art(k)).join('')}</div></section>
    <div class="ex-ribbon" aria-label="Learn, move, explore, belong"><div>${['LEARN','MOVE','EXPLORE','BELONG'].map((s,i)=>`<span style="--accent:${colors[i]}">${s}<b aria-hidden="true">✦</b></span>`).join('')}</div></div>
    <section id="ages" class="ex-ageband"><div class="wrap"><div class="ex-sectionhead"><div><span class="ex-kicker">Small steps. A brighter tomorrow.</span><h2>Growing at their own pace.</h2></div><div class="ex-agebuttons" role="group" aria-label="Age band">${Object.entries(ages).map(([k,a])=>`<button type="button" data-ex-age="${k}" aria-pressed="${k===age()}">${a.name}<small>${a.range}</small></button>`).join('')}</div></div><div id="ex-age-panel" aria-live="polite">${agePanel()}</div></div></section>
    ${window.FFSupporting.teacher()}
    <section id="units" class="ex-year"><div class="wrap"><div class="ex-sectionhead"><div><span class="ex-kicker">The learning year</span><h2>Twelve adventures. Endless curiosity.</h2></div><p>A planned sequence of stories, everyday skills and family connections.</p></div><div class="ex-months" role="group" aria-label="Monthly unit">${D.units.map((u,i)=>`<button type="button" data-ex-month="${i}" aria-pressed="${i===month}" style="--accent:${colors[i%colors.length]}"><span>${MONTHS[i].slice(0,3)}</span><b>${esc(u.title)}</b><small>Unit ${u.n} ${icon('ArrowRight')}</small></button>`).join('')}</div><div id="ex-journey" aria-live="polite">${journey()}</div></div></section>
    <section class="ex-activities"><div class="wrap"><div class="ex-sectionhead"><div><span class="ex-kicker">A little learning, right now</span><h2>Make room for a happy discovery.</h2></div><div class="ex-friendbuttons" role="group" aria-label="Activity friend">${KEYS.map(k=>`<button type="button" data-ex-friend="${k}" aria-pressed="${friend===k}" style="--accent:${friendColors[k]}">${CH[k].n}<small>${CH[k].p}</small></button>`).join('')}</div></div><div id="ex-activity" class="ex-activity" aria-live="polite">${activity()}</div></div></section>
    <section id="family-plan" class="ex-plan"><div class="wrap ex-plangrid"><div><span class="ex-kicker">From classroom to kitchen table</span><h2>Your next little adventure.</h2><p>A family connection from your selected theme week, paired with a short activity for your age band.</p><div class="ex-days" role="group" aria-label="Discovery days">${['Monday','Tuesday','Wednesday','Thursday','Friday'].map(d=>`<label><input type="checkbox" data-ex-day="${d}" ${days.has(d)?'checked':''}><span>${d.slice(0,3)}</span></label>`).join('')}</div><button type="button" class="px-btn px-primary" data-ex-download>${icon('Download')} Save family plan</button><p id="ex-download-status" class="ex-note" role="status"></p></div><div class="ex-planpreview"><span class="ex-planstamp">FUTURES FRIENDS / FAMILY CONNECTION</span><div id="ex-plan-summary" aria-live="polite">${planSummary()}</div><p class="ex-note">Development preview / No account needed</p></div></div></section>
    ${window.FFAdvisors.render('melissa')}
    ${window.FFWholeChild?window.FFWholeChild.callout('curriculum'):''}
    <section id="addons" class="ex-addons"><div class="wrap"><span class="ex-kicker">Keep the curiosity going</span><h2>New seasons. New possibilities.</h2><div class="ex-seasonrow"><details><summary>Summer camp <span>10 themed weeks ${icon('ChevronDown')}</span></summary><ul>${D.summer.map(s=>`<li>${esc(s)}</li>`).join('')}</ul></details><details><summary>Holiday & seasonal units <span>14 planned units ${icon('ChevronDown')}</span></summary><ul>${D.holiday.map(s=>`<li>${esc(s)}</li>`).join('')}</ul></details></div><div class="ex-addonlinks"><a href="#rainbow">${icon('Leaf')} Eat the Rainbow ${icon('ArrowRight')}</a><a href="#readiness">${icon('Heart')} Individual growth ${icon('ArrowRight')}</a><a href="#academy">${icon('BookOpen')} Educator learning ${icon('ArrowRight')}</a></div></div></section>
    <section id="books" class="ex-books"><div class="wrap"><div class="ex-sectionhead"><div><span class="ex-kicker">Stories worth growing with</span><h2>Meet their next favorite friend.</h2></div><p>Planned storybooks and episode pairings. Published editions and finished episodes are not available in this preview.</p></div><div class="grid g2">${D.books.slice(0,4).map(b=>`<article class="card book">${cover(b)}<div><span class="ex-kicker">Story concept</span><h3>${esc(b.title)}</h3><p>${esc(b.log)}</p></div></article>`).join('')}</div><a class="px-btn px-primary" href="#friends">Explore the stories ${icon('ArrowRight')}</a></div></section>
    </div>`;
  function updatePlan(){const el=document.getElementById('ex-plan-summary');if(el)el.innerHTML=planSummary();const status=document.getElementById('ex-download-status');if(status)status.textContent='';}
  function press(attribute,value){document.querySelectorAll(`[${attribute}]`).forEach(b=>b.setAttribute('aria-pressed',String(b.getAttribute(attribute)===String(value))));}
  document.addEventListener('click', e=>{
    const t=e.target.closest('button');if(!t || !t.closest('.ex-curriculum'))return;
    if(t.hasAttribute('data-ex-age')){st.age=t.dataset.exAge;press('data-ex-age',age());document.getElementById('ex-age-panel').innerHTML=agePanel();document.getElementById('ex-activity').innerHTML=activity();updatePlan();}
    if(t.hasAttribute('data-ex-month')){month=Number(t.dataset.exMonth);week=0;press('data-ex-month',month);document.getElementById('ex-journey').innerHTML=journey();updatePlan();}
    if(t.hasAttribute('data-ex-week')){week=Number(t.dataset.exWeek);const container=document.getElementById('ex-journey');container.innerHTML=journey();container.querySelector(`[data-ex-week="${week}"]`).focus();updatePlan();}
    if(t.hasAttribute('data-ex-friend')){friend=t.dataset.exFriend;press('data-ex-friend',friend);document.getElementById('ex-activity').innerHTML=activity();updatePlan();}
    if(t.hasAttribute('data-ex-download')){const url=URL.createObjectURL(new Blob([planText()],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='futures-friends-family-plan.txt';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);document.getElementById('ex-download-status').textContent='Your family plan download has been requested.';}
  });
  document.addEventListener('change',e=>{if(e.target.matches('[data-ex-day]')){const d=e.target.dataset.exDay;e.target.checked?days.add(d):days.delete(d);updatePlan();}});
  window.FFExperience={ages,activities,agePanel,journey,activity,planText};
})();
