/* Futures Hub backend connection.

   PRODUCTION (branch release-platform): FF_HUB_PROD holds the public API address and the PUBLIC anon key of the production
   Supabase (https://ff-api.dvolcore.com). The key line is WRITTEN BY A SCRIPT, never by hand:
     node tools/set-hub-config.mjs /Volumes/FFCRM/app/deploy/out/hub-public.json
   (that file is produced by the CRM repo's deploy/push.sh). The script refuses anything that is not an anon-role JWT, so a
   service-role or secret key can never land here. While anonKey is empty the Teacher and Family portals stay in sample mode,
   exactly as before.

   LOCAL: copy hub-config.local.js.example to hub-config.local.js (git-ignored) and fill in the local Supabase URL and the
   PUBLIC anon key. The local file is only ever loaded from localhost / 127.0.0.1. */
window.FF_HUB_PROD = { url: 'https://ff-api.dvolcore.com', anonKey: '' }; // @generated by tools/set-hub-config.mjs
(function () {
  var h = location.hostname;
  if (h === 'localhost' || h === '127.0.0.1') {
    document.write('<script src="hub-config.local.js"><\/script>');
  } else if (window.FF_HUB_PROD && window.FF_HUB_PROD.anonKey) {
    window.FF_HUB = { url: window.FF_HUB_PROD.url, anonKey: window.FF_HUB_PROD.anonKey };
  }
})();
