/* Resource Library, DEMO side (owner 2026-10-07: "make sure the admin and the teachers, whenever they sign in, can send all this stuff out").
   Mirrors the hosted Futures Hub library with the public rules applied:
     - the catalog (library-catalog.js) and the rules (library-core.js) are generated by the Hub repo; nothing here decides who may see or send;
     - THE IP RULE: an item with no public file shows its title, picture, ages, language and status and the line "Opens in your hosted Futures Hub".
       No link, no file name, no path to a curriculum file is ever written into the page for it. Public items (public.path / public.route) open the
       public file or page, in an in-page dialog;
     - Send queues a record in the demo database (collection libsends) and logs it (liblog). Email is off until the owner's account exists, so
       nothing is delivered; demo accounts are fake and nothing leaves the browser. */
(function () {
'use strict';
const W = window, DM = W.FFDemo, CAT = W.FF_LIBRARY, CORE = W.FFLibraryCore;
if (!DM || !CAT || !CORE) return;
const E = s => String(s == null ? '' : s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ITEMS = CAT.items, IDX = new Map(ITEMS.map((it, i) => [it, i]));
const GROUP_FRIEND = {curriculum:'booker', family:'lumi', menus:'zuri', move:'bop', spanish:'zuri', training:'booker', forms:'bop', room:'lumi', brand:'bop', stories:'lumi', emails:'booker'};
const SAMPLE_RE = /^printables\/sample\//;
const OFF_LINE = 'Sending turns on when email is connected.';
const HUB_LINE = 'Opens in your hosted Futures Hub';
const ST = {q:'', group:'', age:'', lang:'', status:'', unit:'', week:'', day:'', open:{}, start:'', filtersOpen:null, sendFor:null, scope:'all', pick:{}, langs:{}, msg:''};

// ---------------------------------------------------------------- who is signed in
function who(){
  const s = DM.session && DM.session(); if (!s) return null;
  if (s.role === 'director') return {role:'director', id:s.id, name:s.name};
  if (s.role === 'teacher' && DM.can(s.id, 'library')) return {role:'teacher', id:s.id, name:s.name};
  return null;
}
const allowed = () => !!who();
const mine = () => { const w = who(); return w ? CORE.visibleItems(ITEMS, w.role) : []; };
const idx = it => IDX.get(it);
const itemAt = i => ITEMS[Number(i)];
const isPublic = it => !!it.public && (!!it.public.path || !!it.public.route);
const filePath = it => (it.public && it.public.path) || '';
const todayD = () => DM.todayIso();

// ---------------------------------------------------------------- small pieces
const STATUS_ICON = {ready:'✓', draft:'✎', review:'?', soon:'…'};
function chips(it){
  const es = it.lang === 'es' || it.lang === 'bi';
  return `<span class="rl-chip rl-st-${E(it.status)}"><span aria-hidden="true">${STATUS_ICON[it.status] || ''}</span> ${E(CORE.STATUS_LABEL[it.status] || it.status)}</span>
    <span class="rl-chip rl-lang" title="${it.lang === 'es' ? 'Spanish' : it.lang === 'bi' ? 'English and Spanish' : 'English'}">${E(CORE.langLabel(it))}</span>${es && it.draft_es ? '<span class="rl-chip rl-borr" title="Spanish draft: a teacher who speaks Spanish should read it first">BORRADOR</span>' : ''}`;
}
function thumb(it){
  const f = GROUP_FRIEND[it.group] || 'booker';
  return it.thumb ? `<img class="rl-img" src="img/library/${E(it.thumb)}" alt="" loading="lazy" decoding="async" width="320" height="415">`
    : `<span class="rl-img rl-ph" style="--c:var(--${f})" aria-hidden="true"><b>${E(CORE.TYPE_LABEL[it.type] || 'File')}</b></span>`;
}
const sampleLabel = it => isPublic(it) && SAMPLE_RE.test(filePath(it)) && it.kind !== 'sample' ? 'Sample' : 'Preview';
// The approval and audience gate: Send to families only for approved, family-facing items; staff-only and unapproved items go to staff at most.
function sendControl(it, role, i){
  const aud = CORE.audiences(it, role);
  if (aud.indexOf('families') !== -1) return `<button type="button" class="btn navy rl-act" data-lib="send" data-i="${i}" aria-label="Send ${E(it.title)} to families">Send</button>`;
  const staff = aud.indexOf('staff') !== -1 ? `<button type="button" class="btn soft rl-act" data-lib="send" data-i="${i}" aria-label="Send ${E(it.title)} to staff">Send to staff</button>` : '';
  const why = (it.sendable && it.status !== 'soon' && CORE.normRole(role) !== 'none') ? `<span class="rl-hub rl-gate" role="note" title="${E(CORE.sendReason(it, role, 'families'))}"><span aria-hidden="true">⛔</span> ${E(it.status === 'ready' ? 'Staff only' : CORE.NOT_APPROVED)}</span>` : '';
  return why + staff;
}
function actions(it, role){
  const i = idx(it), pub = isPublic(it), p = filePath(it), a = [];
  if (pub) {
    a.push(`<button type="button" class="btn soft rl-act" data-lib="preview" data-i="${i}" aria-label="${sampleLabel(it)} ${E(it.title)}">${sampleLabel(it)}</button>`);
    if (p && /\.(pdf|png|jpe?g|webp|svg|mp4)$/i.test(p)) a.push(`<a class="btn soft rl-act" href="${E(p)}" download data-lib="dl" data-i="${i}" aria-label="Download ${E(it.title)}">Download</a>`);
    if (p && /\.(pdf|png|jpe?g|webp|svg)$/i.test(p)) a.push(`<button type="button" class="btn soft rl-act" data-lib="print" data-i="${i}" aria-label="Print ${E(it.title)}">Print</button>`);
  } else if (it.status !== 'soon') a.push(`<span class="rl-hub" role="note"><span aria-hidden="true">⌂</span> ${HUB_LINE}</span>`);
  else a.push(`<span class="rl-hub" role="note"><span aria-hidden="true">…</span> Not made yet</span>`);
  a.push(sendControl(it, role, i));
  return a.join('');
}
function card(it, role, opt){
  const g = GROUP_FRIEND[it.group] || 'booker', f = CORE.fileLabel(it);
  return `<article class="rl-card${opt && opt.small ? ' rl-small' : ''}" style="--c:var(--${g})" aria-label="${E(it.title)}">
    <div class="rl-thumb">${thumb(it)}${it.d ? `<span class="rl-day">Day ${it.d}</span>` : ''}</div>
    <div class="rl-body"><div class="rl-chips">${chips(it)}</div>
      <h4 class="rl-title">${E(it.title)}</h4>
      <p class="rl-meta">${E(it.sub)} · ${E(CORE.ageLabel(it))}${f ? ' · ' + E(f) : ''}</p>
      ${opt && opt.small ? '' : `<p class="rl-desc">${E(it.desc)}</p>`}
      <div class="rl-acts">${actions(it, role)}</div></div></article>`;
}

// ---------------------------------------------------------------- the page
function filters(){ return {q:ST.q, group:ST.group, age:ST.age, lang:ST.lang, status:ST.status, unit:ST.unit, week:ST.week, day:ST.day}; }
const anyFilter = () => Object.values(filters()).some(Boolean);
function sel(id, label, opts, val){
  return `<label class="f rl-f" for="${id}">${label}<select class="i" id="${id}" data-lib-f="${id.replace('rlF_', '')}">${opts.map(([v, t]) => `<option value="${E(v)}" ${String(v) === String(val) ? 'selected' : ''}>${E(t)}</option>`).join('')}</select></label>`;
}
function filterBar(vis){
  const weeks = [...new Set(vis.map(i => i.cal_week).filter(Boolean))].sort((a, b) => a - b), units = [...new Set(vis.map(i => i.unit).filter(Boolean))].sort((a, b) => a - b);
  const n = ['age', 'lang', 'status', 'unit', 'week', 'day'].filter(k => ST[k]).length;
  const open = ST.filtersOpen == null ? (W.matchMedia && W.matchMedia('(min-width:900px)').matches) : ST.filtersOpen;
  return `<details class="rl-filters" ${open ? 'open' : ''} id="rlFilters"><summary>Filters${n ? ` <span class="rl-n">${n}</span>` : ''}</summary>
   <div class="rl-fgrid">
    ${sel('rlF_age', 'Age', [['', 'Any age'], ...Object.entries(CAT.ages)], ST.age)}
    ${sel('rlF_lang', 'Language', [['', 'English and Spanish'], ['en', 'English'], ['es', 'Spanish']], ST.lang)}
    ${sel('rlF_status', 'Status', [['', 'Any status'], ...Object.entries(CAT.statuses)], ST.status)}
    ${sel('rlF_unit', 'Unit', [['', 'Any unit'], ...units.map(u => [u, 'Unit ' + u])], ST.unit)}
    ${sel('rlF_week', 'Week of the year', [['', 'Any week'], ...weeks.map(w => [w, 'Week ' + w])], ST.week)}
    <label class="f rl-f" for="rlF_day">Day (1 to ${CAT.calendar.school_days})<input class="i" id="rlF_day" data-lib-f="day" type="number" inputmode="numeric" min="1" max="${CAT.calendar.school_days}" value="${E(ST.day)}"></label>
   </div></details>`;
}
function groupTiles(vis){
  const counts = CORE.groupCounts(vis, CAT.groups);
  return `<div class="rl-groups" role="group" aria-label="Library groups">${CAT.groups.map(g => {
    const on = ST.group === g.key, f = GROUP_FRIEND[g.key] || 'booker';
    return `<button type="button" class="rl-g" style="--c:var(--${f})" data-lib="group" data-g="${E(g.key)}" aria-pressed="${on}" title="${E(g.blurb)}"><b>${counts[g.key] || 0}</b><span>${E(g.label)}</span></button>`;
  }).join('')}</div>`;
}
function todayPanel(vis, role){
  const iso = todayD(), start = ST.start || CORE.defaultStart(CORE.fromIso(iso)), tp = CORE.todayPlan(CAT, vis, iso, start);
  const one = (label, it) => it ? `<div class="rl-t"><span class="rl-tl">${label}</span>${card(it, role, {small:true})}</div>` : '';
  const bits = [one('Teacher packet', tp.packet), one('Menu this week', tp.menu), one('Move card', tp.move), one('Family letter', tp.family)].join('');
  return `<section class="rl-today" aria-labelledby="rlTodayH"><div class="rl-thead"><div><h3 id="rlTodayH">Today</h3><p class="rl-lead">${E(tp.label)}</p></div>
    <label class="f rl-f rl-start" for="rlStart">School year starts<input class="i" id="rlStart" type="date" value="${E(start)}" data-lib-f="start"></label></div>
    ${bits ? `<div class="rl-tgrid">${bits}</div>` : `<p class="rl-empty-s">${tp.review ? 'Review day: no new packet. Spend the day on what the children asked for again.' : 'Nothing is lined up for this date yet.'}</p>`}</section>`;
}
function newStrip(vis, role){
  const nw = CORE.newThisWeek(vis, new Date(), 8);
  let list = nw.items, head = 'New this week', note = `${nw.total} added in the last seven days`;
  if (!list.length) { list = vis.filter(i => i.added && i.status !== 'soon').sort((a, b) => a.added < b.added ? 1 : -1).slice(0, 8); head = 'Newest in the library'; note = 'Nothing new in the last seven days'; }
  if (!list.length) return '';
  return `<section class="rl-new" aria-labelledby="rlNewH"><div class="rl-thead"><h3 id="rlNewH">${head}</h3><span class="rl-lead">${E(note)}</span></div>
    <div class="rl-strip" role="list">${list.map(it => `<div role="listitem">${card(it, role, {small:true})}</div>`).join('')}</div></section>`;
}
function results(vis, role){
  if (!anyFilter()) return `<div class="rl-pick"><p><b>Pick a group above or search</b> to see the cards. ${vis.length} items are open to you.</p></div>`;
  const rows = CORE.filterItems(vis, filters());
  if (!rows.length) return `<div class="rl-empty"><img src="img/plush/characters/zuri-480.webp" alt="" width="96" height="96" onerror="this.remove()"><h4>Nothing matches yet</h4><p>Try fewer filters, or search for a word from the title. Items still being written show up under Status, Coming soon.</p><button type="button" class="btn soft" data-lib="clear">Clear filters</button></div>`;
  const secs = CORE.bySub(rows);
  return `<p class="rl-count" role="status" aria-live="polite">${rows.length} ${rows.length === 1 ? 'item' : 'items'}</p>` + secs.map(s => {
    const k = (ST.group || '*') + '|' + s.sub, all = !!ST.open[k], list = all ? s.items : s.items.slice(0, 12);
    return `<section class="rl-sec" aria-label="${E(s.sub)}"><h3 class="rl-sh">${E(s.sub)} <span class="rl-n">${s.items.length}</span></h3><div class="rl-grid">${list.map(it => card(it, role)).join('')}</div>
      ${s.items.length > 12 && !all ? `<button type="button" class="btn soft rl-more" data-lib="more" data-k="${E(k)}">Show all ${s.items.length}</button>` : ''}</section>`;
  }).join('');
}
function sentPanel(role){
  const sends = Object.entries(DM.all('libsends')).sort((a, b) => b[1].at - a[1].at), log = Object.values(DM.all('liblog')).sort((a, b) => b.at - a.at).slice(0, 12);
  const when = t => new Date(t).toLocaleString([], {month:'short', day:'numeric', hour:'numeric', minute:'2-digit'});
  return `<section class="rl-sent" aria-labelledby="rlSentH"><h3 id="rlSentH">Sent items</h3>
   <p class="rl-lead">${E(OFF_LINE)} Until then a send waits here as Queued.</p>
   ${sends.length ? `<ul class="rl-q">${sends.slice(0, 10).map(([id, s]) => `<li><span class="rl-chip rl-st-queued"><span aria-hidden="true">⏳</span> Queued</span><span><b>${E(s.title)}</b><span class="rl-meta">${s.kind === 'staff' ? `${s.recipients.length} staff` : `${s.recipients.length} ${s.recipients.length === 1 ? 'family' : 'families'} (${E(s.scopeLabel)}) · ${s.recipients.filter(r => r.lang === 'es').length} in Spanish`} · ${E(s.byName)}, ${E(when(s.at))}</span></span></li>`).join('')}</ul>`
     : '<p class="rl-empty-s">Nothing queued yet. Pick a card and press Send.</p>'}
   ${role === 'director' ? `<details class="rl-log"><summary>Library activity</summary>${log.length ? `<ul>${log.map(l => `<li><span class="rl-meta">${E(when(l.at))}</span> ${E(l.byName)} ${E(l.what)}: ${E(l.title)}</li>`).join('')}</ul>` : '<p class="rl-empty-s">No activity yet.</p>'}</details>` : ''}</section>`;
}
function page(){
  const w = who(); if (!w) return '';
  const vis = mine(), role = w.role;
  return `<div class="rlib" id="ffLib"><header class="rl-head"><div><p class="rl-eyebrow">${role === 'director' ? 'Director' : 'Teacher'} library</p><h2>Resource Library</h2>
    <p class="rl-lead">Everything we have made, in one place. Find it and look at it. Only approved family items can be sent home.</p></div>
    <div class="rl-stat"><b>${vis.length}</b><span>items open to you${role === 'teacher' ? '. Directors see a few more.' : '.'} ${E(CORE.countsLine(CORE.statusCounts(vis)))}.</span></div></header>
    <p class="rl-demo" role="note">Demo: full curriculum files open in your hosted Futures Hub. Here you see the cards, the public samples, and how sending works.</p>
    ${groupTiles(vis)}
    <div class="rl-bar"><label class="f rl-search" for="rlQ">Search the library<input class="i" id="rlQ" type="search" data-lib-f="q" value="${E(ST.q)}" placeholder="Try &ldquo;rainbow&rdquo;, &ldquo;day 9&rdquo; or &ldquo;Spanish&rdquo;" autocomplete="off"></label>
      ${anyFilter() ? '<button type="button" class="btn soft" data-lib="clear">Clear</button>' : ''}</div>
    ${filterBar(vis)}
    ${anyFilter() ? '' : todayPanel(vis, role) + newStrip(vis, role)}
    <div id="rlRes">${results(vis, role)}</div>
    ${sentPanel(role)}
    <p class="sr-only" id="rlLive" role="status" aria-live="polite"></p></div>`;
}
function paint(){ const el = document.getElementById('ffLib'); if (!el) return; const w = who(); if (!w) return;
  const a = document.activeElement, id = a && a.id, pos = a && a.selectionStart; const y = W.scrollY;
  el.outerHTML = page(); W.scrollTo(0, y);
  if (id) { const n = document.getElementById(id); if (n) { try { n.focus({preventScroll:true}); if (pos != null && n.setSelectionRange && n.type !== 'number' && n.type !== 'date') n.setSelectionRange(pos, pos); } catch (_) {} } } }
function paintResults(){ const el = document.getElementById('rlRes'), w = who(); if (el && w) el.innerHTML = results(mine(), w.role); const c = document.getElementById('rlNote'); if (c) c.remove(); }
const say = m => { const l = document.getElementById('rlLive'); if (l) { l.textContent = ''; setTimeout(() => { l.textContent = m; }, 30); } };

// ---------------------------------------------------------------- home tiles (Director dashboard, Teacher Today)
function tile(){
  const w = who(); if (!w) return '';
  const vis = mine(), nw = CORE.newThisWeek(vis, new Date(), 4), shown = nw.items.length ? nw.items : vis.filter(i => i.thumb && i.status === 'ready').slice(0, 4);
  return `<section class="rl-hero" aria-labelledby="rlHeroH"><div class="rl-hero-t"><p class="rl-eyebrow">Resource Library</p><h3 id="rlHeroH">${E(CORE.countsLine(CORE.statusCounts(vis)))}</h3>
    <p class="rl-lead">Packets, menus, move cards, letters, forms, the brand kit and every email. Only approved items can go to families. ${nw.total ? `${nw.total} new this week.` : ''}</p>
    <button type="button" class="btn navy" data-ptab="library">Open the Library</button></div>
    <div class="rl-hero-s" aria-hidden="true">${shown.map(it => `<span class="rl-hs">${thumb(it)}</span>`).join('')}</div></section>`;
}

// ---------------------------------------------------------------- dialogs
let LAST = null;
function dlg(html, cls){
  closeDlg(true);
  const d = document.createElement('dialog'); d.className = 'rl-dlg ' + (cls || ''); d.setAttribute('aria-labelledby', 'rlDT'); d.innerHTML = html; document.body.appendChild(d);
  d.addEventListener('close', () => { d.remove(); if (LAST && document.contains(LAST)) try { LAST.focus({preventScroll:true}); } catch (_) {} });
  d.addEventListener('click', e => { if (e.target === d) d.close(); });
  d.showModal(); const h = d.querySelector('[autofocus]') || d.querySelector('h2'); if (h) { h.setAttribute('tabindex', '-1'); h.focus(); }
  return d;
}
function closeDlg(quiet){ document.querySelectorAll('dialog.rl-dlg').forEach(d => { if (quiet) d.remove(); else d.close(); }); }
function viewerBody(it){
  const p = filePath(it), r = it.public && it.public.route;
  if (p) {
    if (/\.pdf$/i.test(p)) return `<object class="rl-obj" data="${E(p)}#toolbar=1" type="application/pdf" aria-label="${E(it.title)}"><p>This browser cannot show the PDF here. <a href="${E(p)}" target="_blank" rel="noopener">Open it in a new tab</a>.</p></object>`;
    if (/\.mp4$/i.test(p)) { const b = p.replace(/\.mp4$/i, '');
      return `<video class="rl-vid" controls preload="metadata" playsinline ${it.thumb ? `poster="img/library/${E(it.thumb)}"` : ''}><source src="${E(p)}" type="video/mp4"><track kind="captions" src="${E(b)}.en.vtt" srclang="en" label="English captions" default><track kind="captions" src="${E(b)}.es.vtt" srclang="es" label="Subtítulos en español"></video>`; }
    return `<img class="rl-pimg" src="${E(p)}" alt="${E(it.title)}">`;
  }
  const txt = it.inline ? `<pre class="rl-pre">${E(it.inline)}</pre>` : '';
  return txt + (r ? `<p><button type="button" class="btn gold" data-lib="route" data-r="${E(r)}">Open this page on the site</button></p>` : '');
}
function preview(it, opener){
  LAST = opener;
  const p = filePath(it), samp = SAMPLE_RE.test(p) && it.kind !== 'sample';
  dlg(`<div class="rl-dh"><div><p class="rl-eyebrow">${E(it.sub)}</p><h2 id="rlDT">${E(it.title)}</h2><div class="rl-chips">${chips(it)}</div></div><button type="button" class="btn soft rl-x" data-lib="close" aria-label="Close preview">Close</button></div>
    ${samp ? '<p class="rl-demo" role="note">This is the watermarked Day 9 sample. The real file for this item opens in your hosted Futures Hub.</p>' : ''}
    <div class="rl-view">${viewerBody(it)}</div>
    <div class="rl-dfoot">${p && !/\.mp4$/i.test(p) ? `<a class="btn soft" href="${E(p)}" download data-lib="dl" data-i="${idx(it)}">Download</a>` : ''}${(a => a.indexOf('families') !== -1 ? `<button type="button" class="btn navy" data-lib="send" data-i="${idx(it)}">Send to families</button>` : a.length ? `<button type="button" class="btn soft" data-lib="send" data-i="${idx(it)}">Send to staff</button>` : '')(CORE.audiences(it, who().role))}${CORE.canSend(it, who().role) && CORE.audiences(it, who().role).indexOf('families') === -1 ? `<span class="rl-meta" role="note">${E(CORE.sendReason(it, who().role, 'families'))}</span>` : ''}</div>`, 'rl-wide');
  note('Previewed', it);
}
function famRows(){
  const kids = DM.all('kids'), rooms = DM.all('rooms');
  return Object.entries(kids).filter(([, k]) => k.demo !== false).map(([id, k]) => ({id, name: `${k.first} ${k.last}`, room: k.room, roomName: (rooms[k.room] || {}).name || k.room, lang: k.lang === 'es' ? 'es' : 'en'}));
}
function langOK(it, l){ return it.lang === 'bi' ? true : it.lang === l; }
function sendDialog(it, opener){
  LAST = opener; const w = who(), rooms = Object.entries(DM.all('rooms')).sort((a, b) => (a[1].order || 9) - (b[1].order || 9));
  ST.sendFor = idx(it); ST.scope = 'all'; ST.pick = {}; ST.langs = {};
  ST.audience = CORE.canSendTo(it, w.role, 'families') ? 'families' : 'staff';
  dlg(ST.audience === 'staff' ? staffHtml(it) : sendHtml(it, rooms, w), '');
}
function staffRows(){ return Object.entries(DM.all('staff')).map(([id, s]) => ({id, name: s.name || id, role: s.role || 'Staff'})); }
function staffHtml(it){
  const rows = staffRows();
  return `<div class="rl-dh"><div><p class="rl-eyebrow">Send to staff</p><h2 id="rlDT">${E(it.title)}</h2><div class="rl-chips">${chips(it)}</div></div><button type="button" class="btn soft rl-x" data-lib="close" aria-label="Close">Close</button></div>
   <p class="rl-demo" role="note">${E(OFF_LINE)} Your send waits in the Sent items list as Queued. In this demo nothing leaves your browser.</p>
   <p class="rl-warn" role="note"><b>${E(it.status === 'ready' ? 'Staff only.' : CORE.NOT_APPROVED + '.')}</b> ${E(it.status === 'ready' ? 'This item is for your team, so it can go to staff but not to families.' : 'It is a ' + (it.status === 'review' ? 'review copy' : 'draft') + ', so it can go to staff to read but not to families.')}</p>
   <ul class="rl-fams" aria-label="Staff">${rows.map(r => `<li class="rl-fam"><label class="rl-fc"><input type="checkbox" data-lib-staff="${E(r.id)}" checked> <span><b>${E(r.name)}</b><span class="rl-meta">${E(r.role)}</span></span></label></li>`).join('') || '<li class="rl-empty-s">No staff in this center.</li>'}</ul>
   <p class="rl-count" role="status" aria-live="polite" id="rlSendN">${rows.length} staff selected</p>
   <div class="rl-dfoot"><button type="button" class="btn navy" data-lib="queue" ${rows.length ? '' : 'disabled'}>Queue the send</button></div>
   <p class="rl-meta" id="rlSendMsg" role="status" aria-live="polite"></p>`;
}
function sendHtml(it, rooms, w){
  const fams = famRows(), sc = ST.scope, inScope = f => sc === 'all' || (sc === 'pick' ? true : f.room === sc);
  const checked = f => sc === 'pick' ? !!ST.pick[f.id] : inScope(f);
  const lang = f => { const v = ST.langs[f.id]; return v && langOK(it, v) ? v : langOK(it, f.lang) ? f.lang : (it.lang === 'es' ? 'es' : 'en'); };
  const pub = isPublic(it), p = filePath(it);
  const rowsHtml = fams.filter(f => sc === 'pick' || inScope(f)).map(f => `<li class="rl-fam"><label class="rl-fc"><input type="checkbox" data-lib-fam="${E(f.id)}" ${checked(f) ? 'checked' : ''}> <span><b>${E(f.name)}’s family</b><span class="rl-meta">${E(f.roomName)} · saved language ${f.lang === 'es' ? 'Spanish' : 'English'}</span></span></label>
    <label class="sr-only" for="rlL_${E(f.id)}">Language for ${E(f.name)}’s family</label><select class="i rl-ls" id="rlL_${E(f.id)}" data-lib-lang="${E(f.id)}">${['en', 'es'].map(l => `<option value="${l}" ${lang(f) === l ? 'selected' : ''} ${langOK(it, l) ? '' : 'disabled'}>${l === 'en' ? 'English' : 'Español'}</option>`).join('')}</select></li>`).join('');
  const n = fams.filter(f => (sc === 'pick' || inScope(f)) && checked(f)).length;
  return `<div class="rl-dh"><div><p class="rl-eyebrow">Send to families</p><h2 id="rlDT">${E(it.title)}</h2><div class="rl-chips">${chips(it)}</div></div><button type="button" class="btn soft rl-x" data-lib="close" aria-label="Close">Close</button></div>
   <p class="rl-demo" role="note">${E(OFF_LINE)} Your send waits in the Sent items list as Queued. In this demo nothing leaves your browser.</p>
   ${it.draft_es && it.lang !== 'en' ? '<p class="rl-warn" role="note"><b>BORRADOR.</b> The Spanish is a draft. Have a Spanish-speaking teacher read it before it goes home.</p>' : ''}
   <label class="f" for="rlScope">Who gets it<select class="i" id="rlScope" data-lib-scope="1"><option value="all" ${sc === 'all' ? 'selected' : ''}>Every family in the center</option>${rooms.map(([id, r]) => `<option value="${E(id)}" ${sc === id ? 'selected' : ''}>${E(r.name)}</option>`).join('')}<option value="pick" ${sc === 'pick' ? 'selected' : ''}>Pick families myself</option></select></label>
   ${it.lang === 'bi' || it.lang === 'es' ? '' : '<p class="rl-meta">This item is in English only, so every family gets English.</p>'}
   <ul class="rl-fams" aria-label="Families">${rowsHtml || '<li class="rl-empty-s">No families in this room.</li>'}</ul>
   <p class="rl-count" role="status" aria-live="polite" id="rlSendN">${n} ${n === 1 ? 'family' : 'families'} selected</p>
   <div class="rl-dfoot"><button type="button" class="btn navy" data-lib="queue" ${n ? '' : 'disabled'}>Queue the send</button>
    ${pub && p ? `<button type="button" class="btn soft" data-lib="copy" data-i="${idx(it)}">Copy link</button><a class="btn soft" href="${E(p)}" download data-lib="dl" data-i="${idx(it)}">Download to share</a>`
      : pub ? `<button type="button" class="btn soft" data-lib="copy" data-i="${idx(it)}">Copy link</button>` : ''}</div>
   ${pub ? '' : `<p class="rl-meta">${HUB_LINE}. The family copy is sent from there, so there is no link to copy here.</p>`}
   <p class="rl-meta" id="rlSendMsg" role="status" aria-live="polite"></p>`;
}
function rerenderSend(){ const d = document.querySelector('dialog.rl-dlg'); if (!d || ST.sendFor == null) return; const it = itemAt(ST.sendFor), w = who();
  const a = document.activeElement && document.activeElement.id; d.innerHTML = ST.audience === 'staff' ? staffHtml(it) : sendHtml(it, Object.entries(DM.all('rooms')).sort((x, y) => (x[1].order || 9) - (y[1].order || 9)), w);
  if (a) { const n = document.getElementById(a); if (n) n.focus({preventScroll:true}); } }
async function note(what, it){ const w = who(); if (!w) return;
  await DM.put('liblog', 'l' + Date.now().toString(36) + Math.random().toString(36).slice(2, 5), {what, title:it.title, by:w.id, byName:w.name, at:Date.now()}); }
async function queue(){
  const it = itemAt(ST.sendFor), w = who(); if (!it || !w || !CORE.canSendTo(it, w.role, ST.audience || 'families')) return;   // the gate is enforced here too, not only by hiding the button
  const d = document.querySelector('dialog.rl-dlg');
  if (ST.audience === 'staff') {
    const chosen = [...d.querySelectorAll('[data-lib-staff]')].filter(x => x.checked).map(x => x.dataset.libStaff), all = staffRows();
    const rows = chosen.map(id => ({staff:id, name:(all.find(x => x.id === id) || {}).name || id}));
    if (!rows.length) return;
    const id = 's' + Date.now().toString(36);
    await DM.put('libsends', id, {item:it.id, title:it.title, kind:'staff', scopeLabel:'staff', recipients:rows, status:'queued', by:w.id, byName:w.name, byRole:w.role, at:Date.now(), email:'off'});
    await DM.put('liblog', 'l' + id, {what:'queued a send', title:`${it.title} to ${rows.length} staff`, by:w.id, byName:w.name, at:Date.now()});
    closeDlg(); setTimeout(() => { paint(); say(`Queued for ${rows.length} staff. Nothing is delivered until email is connected.`); }, 30);
    return;
  }
  const fams = famRows(), sc = ST.scope;
  const chosen = [...d.querySelectorAll('[data-lib-fam]')].filter(x => x.checked).map(x => x.dataset.libFam);
  const rows = chosen.map(id => { const f = fams.find(x => x.id === id), s = d.querySelector(`[data-lib-lang="${id}"]`); return {kid:id, family:`${f.name}’s family`, lang:s ? s.value : f.lang}; });
  if (!rows.length) return;
  const rooms = DM.all('rooms'), scopeLabel = sc === 'all' ? 'the whole center' : sc === 'pick' ? 'picked families' : (rooms[sc] || {}).name || sc;
  const id = 's' + Date.now().toString(36);
  await DM.put('libsends', id, {item:it.id, title:it.title, scopeLabel, recipients:rows, status:'queued', by:w.id, byName:w.name, byRole:w.role, at:Date.now(), email:'off'});
  await DM.put('liblog', 'l' + id, {what:'queued a send', title:`${it.title} to ${rows.length} ${rows.length === 1 ? 'family' : 'families'}`, by:w.id, byName:w.name, at:Date.now()});
  closeDlg(); setTimeout(() => { paint(); say(`Queued for ${rows.length} families. Nothing is delivered until email is connected.`); const s = document.getElementById('rlSentH'); if (s) { s.setAttribute('tabindex', '-1'); s.scrollIntoView({block:'start'}); s.focus({preventScroll:true}); } }, 30);
}
function linkFor(it){ const p = filePath(it), r = it.public && it.public.route;
  return p ? new URL(p, location.href).href : r ? location.href.split('#')[0] + '#' + r : ''; }
async function copy(it){
  const u = isPublic(it) ? linkFor(it) : ''; const m = document.getElementById('rlSendMsg');
  if (!u) { if (m) m.textContent = HUB_LINE + '.'; return; }
  try { await navigator.clipboard.writeText(u); if (m) m.textContent = 'Link copied.'; } catch (_) { if (m) m.innerHTML = `Copy this link: <input class="i" readonly value="${E(u)}" aria-label="Link" onfocus="this.select()">`; }
  note('copied a link to', it);
}

// ---------------------------------------------------------------- events
document.addEventListener('click', async e => {
  const t = e.target && e.target.closest ? e.target.closest('[data-lib]') : null; if (!t || !who()) return;
  const a = t.dataset.lib, it = t.dataset.i != null ? itemAt(t.dataset.i) : null;
  if (a === 'dl') { if (it) note('downloaded', it); return; }   // plain <a download>
  e.preventDefault();
  if (a === 'group') { ST.group = ST.group === t.dataset.g ? '' : t.dataset.g; ST.open = {}; paint(); return say(ST.group ? 'Showing ' + t.textContent : 'Showing all groups'); }
  if (a === 'clear') { Object.assign(ST, {q:'', group:'', age:'', lang:'', status:'', unit:'', week:'', day:''}); ST.open = {}; paint(); return; }
  if (a === 'more') { ST.open[t.dataset.k] = true; paintResults(); return; }
  if (a === 'close') return closeDlg();
  if (a === 'route') { closeDlg(); location.hash = '#' + t.dataset.r; return; }
  if (a === 'preview' && it) { const r = it.public && it.public.route; if (r && !it.inline && !filePath(it)) { note('opened', it); location.hash = '#' + r; return; } return preview(it, t); }
  if (a === 'print' && it) { const p = filePath(it); note('printed', it); if (p) W.open(p, '_blank', 'noopener'); say('Opened in a new tab. Use Print there.'); return; }
  if (a === 'send' && it) { const o = document.querySelector('dialog.rl-dlg') ? LAST : t; closeDlg(true); return sendDialog(it, o && document.contains(o) ? o : t); }
  if (a === 'queue') return queue();
  if (a === 'copy' && it) return copy(it);
});
document.addEventListener('input', e => {
  const t = e.target; if (!t || !t.dataset || !who()) return;
  if (t.dataset.libF === 'q') { ST.q = t.value; return paintResults2(); }
  if (t.dataset.libF === 'day') { ST.day = t.value; return paintResults2(); }
});
function paintResults2(){ // search and day change the page shape (the Today and New strips hide), so repaint everything but keep the field
  paint(); }
document.addEventListener('change', e => {
  const t = e.target; if (!t || !t.dataset) return;
  if (t.dataset.libF && who()) { const k = t.dataset.libF; if (k === 'start') ST.start = t.value; else if (k !== 'q' && k !== 'day') ST[k] = t.value; ST.filtersOpen = true; paint(); return; }
  if (t.dataset.libScope) { ST.scope = t.value; ST.pick = {}; return rerenderSend(); }
  if (t.dataset.libFam) { ST.pick[t.dataset.libFam] = t.checked; if (ST.scope !== 'pick') { ST.scope = 'pick'; fams2pick(t.dataset.libFam, t.checked); return rerenderSend(); } const n = document.querySelectorAll('dialog.rl-dlg [data-lib-fam]:checked').length; const el = document.getElementById('rlSendN'); if (el) el.textContent = `${n} ${n === 1 ? 'family' : 'families'} selected`; const q = document.querySelector('[data-lib="queue"]'); if (q) q.disabled = !n; return; }
  if (t.dataset.libStaff != null) { const n = document.querySelectorAll('dialog.rl-dlg [data-lib-staff]:checked').length, el = document.getElementById('rlSendN'); if (el) el.textContent = `${n} staff selected`; const q = document.querySelector('[data-lib="queue"]'); if (q) q.disabled = !n; return; }
  if (t.dataset.libLang) ST.langs[t.dataset.libLang] = t.value;
});
// moving from a room or everyone to "pick": keep who was checked
function fams2pick(changedId, val){ const d = document.querySelector('dialog.rl-dlg'); if (!d) return; ST.pick = {}; d.querySelectorAll('[data-lib-fam]').forEach(x => { ST.pick[x.dataset.libFam] = x.dataset.libFam === changedId ? val : x.checked; }); }
document.addEventListener('toggle', e => { if (e.target && e.target.id === 'rlFilters') ST.filtersOpen = e.target.open; }, true);

W.FFLibraryDemo = {allowed, who, view:page, tile, state:ST};
})();
