/* Futures Friends Unit 1: "Prep ahead this week" on the teacher Today view (R2-N4, W3D).
   Later blocks in a week (mostly Friday) use things made, collected or kept on earlier days: a substitute who arrives on Friday
   cannot make them on the day. The list is the same one each Monday teacher packet prints. Data: the private prep list generated by
   tools/make-unit1-packets.py from FFCRM hub/content/program/unit-1-prep-ahead.json. IP lockdown (owner decision 2026-10-07): that file
   is licensed curriculum and is NOT on the website; this module draws it only when a hosted Futures Hub supplies window.FFUnit1Prep.
   ETEACH E7: the same data file carries each day's deduplicated supply list, drawn above the prep list (teach-day.js renders it).
   Read-only: it draws a list and writes nothing. Labelled draft, like the rest of Unit 1, until a reviewer approves it.
   portal.js calls FFPrepAhead.today(programInfo) at the top of the Today checklist. */
(function(){
'use strict';
const E = s => String(s == null ? '' : s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const D = () => (window.FFGate && window.FFGate.staff() ? window.FFUnit1Prep : null);
const days = refs => (refs || []).map(x => `Day ${E(x.day)} (${E(x.block)})`).join('; ');

// IP lockdown: the public site never requests curriculum data (curriculum-gate.js). Nothing to load.
function ensure(){ return false; }

// items for a week, each with where today sits: 'make' (made or kept today), 'use' (used today), 'keep' (made already, used later)
function forDay(release, week, day){
  const d = D(); if (!d || d.release !== release) return null;
  const w = (d.weeks || []).find(x => x.week === week); if (!w) return null;
  const today = (week - 1) * 5 + day;
  return w.items.map(i => {
    const made = i.from.map(x => x.day), used = i.for.map(x => x.day);
    const when = made.includes(today) ? 'make' : used.includes(today) ? 'use' : Math.max(...made) < today && Math.max(...used) > today ? 'keep' : '';
    return Object.assign({}, i, {when, done: Math.max(...used) < today});
  });
}

const CHIP = {make:['ok','Today: keep it when it is made'], use:['warn','Used today'], keep:['dim','Keep it until it is used']};
function today(pi){
  const x = pi && pi.records && pi.records[0]; if (!x) return '';
  if (x.release !== 'unit-1') return '';
  if (!D()) { ensure(); return ''; }
  // E7: the day's one deduplicated supply list (same list the packet and the Start Monday file print)
  const sup = ((D().supplies || {})[String((x.week - 1) * 5 + x.day)]) || [];
  const supHtml = sup.length && window.FFTeach ? `<section class="card pa-card">${window.FFTeach.supplies(sup)}</section>` : '';
  const items = forDay(x.release, x.week, x.day); if (!items || !items.length) return supHtml;
  const open = items.filter(i => !i.done), past = items.length - open.length;
  if (!open.length) return supHtml;
  return supHtml + `<section class="card pa-card" aria-labelledby="pa-h">
   <div class="pa-head"><h3 id="pa-h" style="margin:0">Prep ahead this week</h3><span class="chip warn">Draft list, not reviewed</span></div>
   <p class="small" style="margin:0">Later blocks this week use things made, collected or kept on earlier days. A substitute cannot make them on the day, so keep each one when it is made. Same list as the Monday packet.</p>
   <ul class="pa-list">${open.map(i => `<li><div class="pa-row"><b>${E(i.item)}</b>${i.when ? ` <span class="chip ${CHIP[i.when][0]}">${E(CHIP[i.when][1])}</span>` : ''}</div>
     <span class="mini">From ${days(i.from)} · used on ${days(i.for)}</span><span class="small">${E(i.do)}</span></li>`).join('')}</ul>
   ${past ? `<p class="mini muted" style="margin:0">${past} earlier item${past === 1 ? '' : 's'} this week already used.</p>` : ''}</section>`;
}

(function css(){
  if (typeof document === 'undefined' || !document.getElementById || document.getElementById('ff-prep-css') || !document.head) return;
  const s = document.createElement('style'); s.id = 'ff-prep-css'; s.textContent = `
.pa-card{display:grid;gap:8px;border-top:5px solid var(--gold)}
.pa-head{display:flex;gap:8px;align-items:center;justify-content:space-between;flex-wrap:wrap}
.pa-list{margin:0;padding-left:18px;display:grid;gap:8px}
.pa-list li{display:grid;gap:2px;min-width:0;overflow-wrap:anywhere}
.pa-row{display:flex;gap:6px;align-items:center;flex-wrap:wrap}
`; document.head.appendChild(s);
})();

window.FFPrepAhead = {today, forDay, ensure};
})();
