/* GENERATED by hub/scripts/load-program.mjs from hub/content/program: the APPROVED current version of each daily-program record.
   Do not edit by hand. Sample mode (no Futures Hub) reads this; hub mode reads the same records from the hub (program_day). */
window.FF_PROGRAM = {"records":[]};
