// One versioned daily-program record (review H3; program-record.js, program-data.js, portal.js Today / calendar / sample family view,
// family-report.js). Sample mode in a sandbox with a SYNTHETIC fixture in the shared record shape (tests/fixtures, a copy of the hub's
// hub/tests/fixtures/program-records.fixture.json); hub mode with a fake signed-in client. The database rules (append-only versions,
// one correction reaching Today, calendar, kitchen and the family continuation, frozen sent reports) are tested in the hub repo:
// hub/tests/program-records.test.mjs.
const P = require('./private-curriculum');
const test = P.gated(require('node:test'), 'curriculum-indicators.js');   // the portal runs here with the PRIVATE Learning Steps (IP lockdown)
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');

const read = (f) => fs.readFileSync(path.join(__dirname, '..', f), 'utf8');
const FIX = JSON.parse(read('tests/fixtures/program-records.fixture.json'));
const START = '2026-08-10', TUE = '2026-08-11', WED = '2026-08-12';
const approved = (recs) => recs.filter((r) => r.status === 'approved');
const visible = (html) => html.replace(/<style[\s\S]*?<\/style>/g, '').replace(/<[^>]+>/g, ' ').replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&amp;/g, '&').replace(/\s+/g, ' ');

// The site in a sandbox (same harness as learning-steps.test.js) with the fixture as program-data.js.
function site(records = approved(FIX)) {
  const handlers = { click: [], change: [] }, store = {};
  const el = () => ({ hidden: true, textContent: '', innerHTML: '', value: '', focus() {}, scrollIntoView() {}, setAttribute() {}, appendChild() {} });
  const toastEl = el(), viewEl = el();
  const c = {
    console, setTimeout: () => 0, clearTimeout() {}, setInterval: () => 0, matchMedia: () => ({ matches: true }),
    localStorage: { getItem: (k) => store[k] ?? null, setItem: (k, v) => { store[k] = String(v); } },
    document: { addEventListener: (t, f) => { (handlers[t] = handlers[t] || []).push(f); }, getElementById: () => null,
      querySelector: (q) => q === '#toast' ? toastEl : q === '#view' ? viewEl : null, querySelectorAll: () => [], createElement: el, head: el(), body: el() },
    location: { hash: '' }, history: { replaceState() {} }, addEventListener() {}, scrollTo() {},
  };
  c.window = c; vm.createContext(c);
  for (const f of ['data.js', 'views.js', 'curriculum-indicators.js', 'portal.js']) vm.runInContext(f === 'curriculum-indicators.js' ? P.readPriv(f) : read(f), c, { filename: f });
  c.FF_PROGRAM = { records, sample_start: START };
  vm.runInContext(read('teach-day.js'), c, { filename: 'teach-day.js' });
  vm.runInContext(read('program-record.js'), c, { filename: 'program-record.js' });
  vm.runInContext("view='portal'", c);
  const fire = async (type, target) => { for (const h of handlers[type]) await h({ target }); };
  const node = (attrs, extra = {}) => Object.assign({ dataset: attrs, closest(sel) { const m = /^\[data-([a-z0-9-]+)\]$/.exec(sel); if (!m) return null; const key = m[1].replace(/-([a-z])/g, (_, x) => x.toUpperCase()); return key in attrs ? this : null; } }, extra);
  const html = (v) => vm.runInContext(`view=${JSON.stringify(v)}; V[${JSON.stringify(v)}]()`, c);
  const setDate = (d) => fire('change', node({}, { id: 'pDate', value: d }));
  return { c, html, fire, node, setDate, toast: () => toastEl.textContent };
}
const ROOM3 = ['k10', 'k11', 'k12', 'k13', 'k14'];   // Mia, Noah, Aria, Liam, Nova (sample Threes Room)

test('program-record.js and program-data.js parse; index.html loads them after the portal and the report, with cache-busting versions', () => {
  new Function(read('program-record.js')); new Function(read('program-data.js'));
  assert.match(read('program-data.js'), /^\/\* GENERATED by hub\/scripts\/load-program\.mjs/);
  assert.match(read('program-data.js'), /window\.FF_PROGRAM = \{"records":\[/);
  const index = read('index.html'), at = (f) => index.indexOf(f);
  assert.ok(at('portal.js') < at('program-data.js') && at('family-report.js') < at('program-data.js') && at('program-data.js') < at('program-record.js'));
  for (const f of ['program-data.js', 'program-record.js', 'portal.js', 'family-report.js']) {
    const m = new RegExp(`${f.replace('.', '\\.')}\\?v=(\\d+)`).exec(index); assert.ok(m && +m[1] >= 1, f);
  }
  assert.ok(+/portal\.js\?v=(\d+)/.exec(index)[1] >= 18 && +/family-report\.js\?v=(\d+)/.exec(index)[1] >= 2, 'edited files are re-versioned');
});

test('the date picks the record: week = whole weeks since the Monday start + 1, day = weekday; drafts never show', () => {
  const s = site(), P = s.c.FFProgram;
  assert.deepEqual(JSON.parse(JSON.stringify(P.slot(START, START))), { week: 1, day: 1 });
  assert.deepEqual(JSON.parse(JSON.stringify(P.slot(START, '2026-08-21'))), { week: 2, day: 5 });
  assert.equal(P.slot(START, '2026-08-07'), null); assert.equal(P.slot(START, '2026-08-15'), null);
  const ctx = { hub: false, rooms: { threes: { name: 'Threes Room' } } };
  assert.deepEqual(P.day(ctx, 'threes', START).records.map((x) => x.block), ['circle', 'story']);
  assert.deepEqual(P.day(ctx, 'threes', TUE).records.map((x) => x.id), ['u1-w1-d2-circle']);
  assert.deepEqual(P.day(ctx, 'threes', WED).records, []);
  assert.deepEqual(site(FIX).c.FFProgram.day(ctx, 'threes', WED).records, [], 'a draft in the bundle is still not shown');
  assert.deepEqual(Object.keys(P.month(ctx, 'threes', '2026-08-01', '2026-08-31')), [START, TUE]);
  assert.deepEqual(JSON.parse(JSON.stringify(P.kitchen(ctx, START).map((k) => [k.room, k.kitchen_prompt]))), [['threes', 'At snack, ask: what color is your cup?']]);
});

test('Today: the approved record replaces the outline, with the room\'s age adaptations (a missing band says so) and real media status', async () => {
  const s = site(); await s.setDate(START);
  const out = s.html('portal'), t = visible(out);
  assert.match(t, /Unit 1 · Week 1 · Day 1 · sample schedule/);
  assert.match(t, /TEST Hello, Friends/);
  assert.match(t, /Lumi · BELONG/);
  assert.match(t, /Threes: Pass the Lumi puppet and say a friend's name\./);
  assert.match(t, /Everyone can join Participation choices A child may wave or hold up a name card instead of speaking\. Movement alternative Not written yet\. Meal reference No food in this block\. Family connection Not written yet\./);
  assert.match(t, /Timing blocks \(estimates, editable\)/); assert.match(t, /about 25 min \(estimate\) of planned blocks/);
  assert.match(t, /Puppet: printables\/lumi-puppet\.pdf Ready/); assert.match(t, /Video: video\/hello-friends\.mp4 Not available yet/); assert.match(t, /Print: printables\/hello-story\.pdf Draft/);
  assert.match(t, /Kitchen learning prompt \(optional talk at the table, never a serving or care instruction\): At snack, ask: what color is your cup\?/);
  assert.match(t, /Offered only to families of children you log as taking part/);
  assert.match(t, /Record u1-w1-d1-circle · version 1 · approved/);
  assert.match(t, /Morning circle: TEST Hello, Friends/, 'the checklist reads the record\'s theme');
  assert.doesNotMatch(t, /curriculum outline/);
  assert.match(t, /Mark who is here first/, 'nobody is logged before attendance');
  await s.fire('change', s.node({}, { id: 'pRoom', value: 'twos' }));
  const twos = visible(s.html('portal'));
  assert.match(twos, /Twos: Sing the hello song and wave to one friend\./);
  assert.match(twos, /Twos: No twos adaptation in this record yet\./, 'the story record has no twos adaptation: shown as missing');
  await s.setDate(WED);
  assert.match(visible(s.html('portal')), /No approved daily-program record for this day .* This is the curriculum outline\./);
});

test('no records released: Today keeps the outline and says it is not an approved record', async () => {
  const s = site([]); await s.setDate(START);
  assert.match(visible(s.html('portal')), /No approved daily-program records are released yet\. This is the curriculum outline, not an approved activity record\./);
});

// E4: participation is unknown until a teacher records it, child by child or through the deliberate "Everyone here took part" action.
// what the circle card says about one child: null (not marked here, so no row), 'none' (Not recorded) or the recorded entry
// {took, by, time, v, group}. The row is drawn from the stored entry (took_part, by, at, v, via).
const NAMES = { k10: 'Mia C.', k11: 'Noah J.', k12: 'Aria Q.', k13: 'Liam X.', k14: 'Nova E.' };
const kidLog = (s, kid) => {
  const t = visible(s.html('portal')).split('Record u1-w1-d1-circle')[0];
  const m = new RegExp(`${NAMES[kid].replace('.', '\\.')} Took part Not this time Not recorded (Recorded: (took part|not this time) · ([^·]+?) · (\\d+:\\d\\d [AP]M) · version (\\d+)( · "everyone here" action)?|Not recorded)`).exec(t);
  if (!m) return null;
  return m[1] === 'Not recorded' ? 'none' : { took: m[2] === 'took part', by: m[3], time: m[4], v: +m[5], group: !!m[6] };
};
const choose = (s, kid, value, rid = 'u1-w1-d1-circle') => s.fire('change', s.node({ progKid: kid, progRec: rid }, { value }));
test('E4: a child marked here but untouched stays "Not recorded"; nothing is pre-selected and an empty save writes nothing', async () => {
  const s = site(); await s.setDate(START);
  for (const k of ['k10', 'k11', 'k12']) await s.fire('click', s.node({ att: k, v: '1' }));        // Mia, Noah, Aria here; Liam, Nova not marked
  const html = s.html('portal'), t = visible(html);
  assert.match(t, /0 took part · 0 not this time · 5 not recorded/);
  assert.doesNotMatch(html, /value="yes"[^>]*checked|checked[^>]*value="yes"/, 'no child starts as "Took part"');
  assert.equal((html.match(/value="" data-prog-kid="k1\d" data-prog-rec="u1-w1-d1-circle" checked/g) || []).length, 3, 'each child here starts on "Not recorded"');
  await s.fire('click', s.node({ progSave: 'u1-w1-d1-circle', progV: '1' }));
  assert.match(s.toast(), /^Nothing to save yet/);
  for (const k of ['k10', 'k11', 'k12']) assert.equal(kidLog(s, k), 'none', `${k}: nothing written`);
  assert.doesNotMatch(read('portal.js'), /prev\.took_part : true\)/, 'the old default-true is gone');
});

test('E4: "Save these choices" writes only the children the teacher marked, with who, when, the record version and how', async () => {
  const s = site(); await s.setDate(START);
  for (const k of ['k10', 'k11', 'k12']) await s.fire('click', s.node({ att: k, v: '1' }));
  await choose(s, 'k10', 'yes'); await choose(s, 'k11', 'no');
  await s.fire('click', s.node({ progSave: 'u1-w1-d1-circle', progV: '1' }));
  assert.equal(s.toast(), 'Saved: 1 took part, 1 not this time');
  assert.deepEqual(kidLog(s, 'k10'), { took: true, by: 'you (demo)', time: kidLog(s, 'k10').time, v: 1, group: false });
  assert.deepEqual([kidLog(s, 'k11').took, kidLog(s, 'k11').group], [false, false]);
  assert.equal(kidLog(s, 'k12'), 'none', 'Aria was not marked: still not recorded');
  const t = visible(s.html('portal'));
  assert.match(t, /1 took part · 1 not this time · 3 not recorded/);
  assert.match(t, /Recorded: took part · you \(demo\) · \d+:\d\d [AP]M · version 1/);
  await s.fire('click', s.node({ progSave: 'u1-w1-d1-circle', progV: '1' }));
  assert.match(s.toast(), /^Nothing to save yet/, 'saving again writes nothing twice');
});

test('E4: "Everyone here took part" is a deliberate two-step action that lists its exceptions; it never includes a child not marked here', async () => {
  const s = site(); await s.setDate(START);
  for (const k of ['k10', 'k11', 'k12']) await s.fire('click', s.node({ att: k, v: '1' }));
  await choose(s, 'k11', 'no');                                                                      // Noah: the exception
  await s.fire('click', s.node({ progAll: 'u1-w1-d1-circle' }));                                    // step 1 only shows the plan
  for (const k of ['k10', 'k11', 'k12']) assert.equal(kidLog(s, k), 'none', 'step 1 writes nothing');
  const t = visible(s.html('portal'));
  assert.match(t, /Everyone here took part\? This records "took part" for Aria Q\., Mia C\. \(2\), by you, now, against record version 1\./);
  assert.match(t, /Exceptions \(not this time\): Noah J\./);
  assert.match(t, /Children not marked here today are never included\./);
  await s.fire('click', s.node({ progAllCancel: 'u1-w1-d1-circle' }));
  assert.doesNotMatch(visible(s.html('portal')), /Exceptions \(not this time\)/, 'cancel closes it');
  await s.fire('click', s.node({ progAllOk: 'u1-w1-d1-circle', progV: '1' }));
  assert.equal(kidLog(s, 'k10'), 'none', 'confirm without the first step does nothing');
  await s.fire('click', s.node({ progAll: 'u1-w1-d1-circle' }));
  await s.fire('click', s.node({ progAllOk: 'u1-w1-d1-circle', progV: '1' }));
  assert.equal(s.toast(), 'Saved: 2 took part (everyone here), 1 not this time');
  assert.deepEqual(kidLog(s, 'k10'), { took: true, by: 'you (demo)', time: kidLog(s, 'k10').time, v: 1, group: true });
  assert.deepEqual(kidLog(s, 'k12'), { took: true, by: 'you (demo)', time: kidLog(s, 'k12').time, v: 1, group: true });
  assert.deepEqual([kidLog(s, 'k11').took, kidLog(s, 'k11').group], [false, false]);
  for (const k of ['k13', 'k14']) assert.equal(kidLog(s, k), null, `${k} was not marked here: no row, nothing recorded`);
  const after = visible(s.html('portal'));
  assert.match(after, /2 took part · 1 not this time · 2 not recorded/);
  assert.match(after, /2 not marked here today: not included\./);
  assert.match(after, /"everyone here" action/);
});

test('E4: a later "Everyone here" never overturns a recorded "Not this time"', async () => {
  const s = site(); await s.setDate(START);
  for (const k of ['k10', 'k11']) await s.fire('click', s.node({ att: k, v: '1' }));
  await choose(s, 'k11', 'no'); await s.fire('click', s.node({ progSave: 'u1-w1-d1-circle', progV: '1' }));
  await s.fire('click', s.node({ progAll: 'u1-w1-d1-circle' }));
  assert.match(visible(s.html('portal')), /Exceptions \(not this time\): Noah J\./);
  await s.fire('click', s.node({ progAllOk: 'u1-w1-d1-circle', progV: '1' }));
  assert.equal(kidLog(s, 'k11').took, false);
  assert.equal(kidLog(s, 'k10').took, true);
});

async function loggedSite(records) {
  const s = site(records); await s.setDate(START);
  for (const k of ['k10', 'k11', 'k12']) await s.fire('click', s.node({ att: k, v: '1' }));
  await choose(s, 'k11', 'no');
  await s.fire('click', s.node({ progAll: 'u1-w1-d1-circle' }));
  await s.fire('click', s.node({ progAllOk: 'u1-w1-d1-circle', progV: '1' }));
  return s;
}
const family = async (s, kid) => { await s.fire('change', s.node({}, { id: 'fKid', value: kid })); await s.fire('change', s.node({}, { id: 'fDate', value: START })); return visible(s.html('family-portal')); };

test('sample family view: continuation only for a child logged as taking part; nothing logged reads "not recorded"; no claims', async () => {
  const s = await loggedSite();
  const mia = await family(s, 'k10');
  assert.match(mia, /The room's lesson: TEST Hello, Friends with Lumi \(BELONG\)/);
  assert.match(mia, /Took part in: Circle: "TEST Hello, Friends" with Lumi/);
  assert.match(mia, /Not recorded: whether Mia joined Story: "TEST Hello, Friends" with Booker was not recorded today\./);
  assert.match(mia, /Try at home \(optional\): TEST Hello Song at Home Sing the hello song at dinner\./);
  assert.match(mia, /Talk about it tonight: Mia took part in "TEST Hello, Friends" with Lumi\./);
  const noah = await family(s, 'k11');                                                   // logged: not this time
  assert.doesNotMatch(noah, /Took part in|Try at home \(optional\)|took part in "/);   // ("Try at home" alone is the Learning Steps section)
  assert.match(noah, /Talk about it tonight: Ask Noah: "What is one thing you did today that you want to tell me about\?"/);
  const liam = await family(s, 'k13');                                                   // not marked here, nothing logged
  assert.match(liam, /Not recorded: whether Liam joined Circle: .*; Story: .* was not recorded today\./);
  assert.doesNotMatch(liam, /Took part in|Try at home \(optional\)/);
  for (const t of [mia, noah, liam]) assert.doesNotMatch(t, /everyone|all children|the whole class (did|took)/i);
});

test('E4: the family view and continuation follow only an explicit "took part": a child here but untouched reads "not recorded"', async () => {
  const s = site(); await s.setDate(START);
  for (const k of ['k10', 'k12']) await s.fire('click', s.node({ att: k, v: '1' }));            // Mia and Aria here
  await choose(s, 'k10', 'yes'); await s.fire('click', s.node({ progSave: 'u1-w1-d1-circle', progV: '1' }));
  const mia = await family(s, 'k10'), aria = await family(s, 'k12');
  assert.match(mia, /Try at home \(optional\): TEST Hello Song at Home/);
  assert.doesNotMatch(aria, /Took part in|Try at home \(optional\)|took part in "/);
  assert.match(aria, /Not recorded: whether Aria joined Circle: .*was not recorded today\./);
});

test('one approved correction (version 2) reaches Today, the calendar, the kitchen prompt and the family continuation with no other edit', async () => {
  const v2 = { ...FIX[0], version: 2, theme: 'TEST Hello, Friends (corrected)', kitchen_prompt: 'At snack, ask: which friend sits next to you?',
               home_continuation: { title: 'TEST Name Song at Home', steps: ['Sing each name at dinner.'], materials_from_home: [] } };
  const s = await loggedSite(approved(FIX).filter((r) => r.id !== v2.id).concat([v2]));   // the regenerated bundle: newest approved version only
  const today = visible(s.html('portal'));
  assert.match(today, /TEST Hello, Friends \(corrected\)/); assert.match(today, /Record u1-w1-d1-circle · version 2 · approved/);
  assert.match(today, /At snack, ask: which friend sits next to you\?/);
  await s.fire('click', s.node({ ptab: 'calendar' }));
  assert.match(visible(s.html('portal')), /TEST Hello, Friends \(corrected\) · 2 activities/);
  assert.deepEqual(JSON.parse(JSON.stringify(s.c.FFProgram.kitchen({ hub: false, rooms: { threes: { name: 'Threes Room' } } }, START).map((k) => [k.version, k.kitchen_prompt]))), [[2, 'At snack, ask: which friend sits next to you?']]);
  const mia = await family(s, 'k10');
  assert.match(mia, /Try at home \(optional\): TEST Name Song at Home/);
  assert.match(mia, /Took part in: Circle: "TEST Hello, Friends \(corrected\)"/, 'the participation logged against version 1 still counts');
});

// ---------------------------------------------------------------- hub mode
function hubProgram(rpc) {
  const calls = [], c = { console, esc: (s) => String(s), FFcut: () => '', document: { getElementById: () => null, createElement: () => ({}), head: { appendChild() {} } } };
  c.window = c; vm.createContext(c);
  c.FFHub = { configured: true, connected: true, client: () => ({ rpc: async (fn, args) => { calls.push([fn, JSON.parse(JSON.stringify(args))]); return rpc[fn]; } }) };
  c.FFPortal = { rerender() {} };
  vm.runInContext(read('program-record.js'), c);
  return { P: c.FFProgram, calls, flush: () => new Promise((r) => setImmediate(r)) };
}
test('hub mode: the hub picks the approved version (program_day / program_calendar / program_kitchen_prompts); a peek never asks', async () => {
  const rec = { id: 'u1-w1-d1-circle', version: 3, release: 'unit-1', block: 'circle', week: 1, day: 1, record: FIX[0] };
  const h = hubProgram({ program_day: { data: { records: [rec], schedule: [{ release: 'unit-1', start_date: START }], releases: ['unit-1'] }, error: null },
    program_calendar: { data: [{ date: START, records: [{ id: rec.id, version: 3, block: 'circle', theme: 'T', character: 'lumi' }] }], error: null },
    program_kitchen_prompts: { data: [{ room: 'threes', version: 3, kitchen_prompt: 'K' }], error: null } });
  const ctx = { hub: true, role: 'teacher', center: { id: 'c1' } };
  assert.equal(h.P.day(ctx, 'threes', START, true).state, 'loading'); assert.equal(h.calls.length, 0, 'peek: no request');
  assert.equal(h.P.day(ctx, 'threes', START).state, 'loading'); await h.flush();
  assert.equal(h.P.day(ctx, 'threes', START).records[0].version, 3);
  assert.deepEqual(h.calls[0], ['program_day', { p_center: 'c1', p_room: 'threes', p_date: START }]);
  h.P.month(ctx, 'threes', '2026-08-01', '2026-08-31'); await h.flush();
  assert.equal(h.P.month(ctx, 'threes', '2026-08-01', '2026-08-31')[START][0].version, 3);
  h.P.kitchen(ctx, START); await h.flush();
  assert.deepEqual(JSON.parse(JSON.stringify(h.P.kitchen(ctx, START))), [{ room: 'threes', version: 3, kitchen_prompt: 'K' }]);
  assert.equal(h.calls.length, 3, 'one request each, then cached');
  assert.deepEqual(JSON.parse(JSON.stringify(h.P.day({ ...ctx, role: 'family' }, 'threes', START).records)), [], 'families read the published report, not plans');
});

test('one publisher in hub mode: the screen-built family report is retired for families; staff are sent to the Family reports preview', () => {
  const portal = read('portal.js');
  assert.match(portal, /if \(P\.hub\) return FR_ANCHOR \+ \(P\.role==='family' \? '' :/);
  assert.match(portal, /out = out\.replace\(FR_ANCHOR, \(\)=>rep\+FR_ANCHOR\)/);
  assert.match(portal, /if\(rp\)\{ if\(P\.hub && window\.FFReport\)\{ P\.tab='reports'; return render\(\); \}/);
  const report = read('family-report.js');
  assert.match(report, /out\.push\(\['Took part in'/); assert.match(report, /out\.push\(\['Not recorded'/);
  assert.match(report, /\$\{tryHome\(r\)\}/);
});

test('family-report.js draws the hub\'s participation lines and the matched continuation, escaped', () => {
  const c = { console, esc: (s) => String(s).replace(/[&<>"']/g, (x) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[x])),
    document: { addEventListener() {}, getElementById: () => null, createElement: () => ({}), head: { appendChild() {} } } };
  c.window = c; vm.createContext(c); vm.runInContext(read('family-report.js'), c);
  const lines = c.FFReport.lines({ first: 'Ava', attendance: { present: true }, lesson: { theme: 'T', friend: 'Lumi', pillar: 'BELONG' },
    program: [{ block: 'circle', theme: 'T', friend: 'Lumi', took_part: true }, { block: 'story', theme: 'T', friend: 'Booker', took_part: null }, { block: 'move', theme: 'T', friend: 'Bop', took_part: false }] });
  assert.deepEqual(JSON.parse(JSON.stringify(lines.slice(1))), [["The room's lesson", '"T" with Lumi (BELONG)'], ['Took part in', 'Circle: "T" with Lumi'],
    ['Not recorded', 'Whether Ava joined Story: "T" with Booker was not recorded today']]);
});

test('a record with no time estimate (the released Unit 1 meal blocks) says so instead of inventing one', async () => {
  const s = site([{ ...FIX[0], duration_min_estimate: null, block: 'picture-talk' }]); await s.setDate(START);
  const t = visible(s.html('portal'));
  assert.match(t, /Picture talk · time not estimated · Lumi/);
  assert.doesNotMatch(t, /about null min/);
});
